// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using Pulumi;

namespace Unilake.Iac.Kubernetes.Custom.Crds.StarRock.V1Alpha1.Inputs
{

    public class StarRocksClusterSpecStarrocksfespecArgs : global::Pulumi.ResourceArgs
    {
        [Input("affinity")]
        public Input<StarRocksClusterSpecStarrocksfespecAffinityArgs>? Affinity { get; set; }

        [Input("annotations")]
        private InputMap<string>? _annotations;
        public InputMap<string> Annotations
        {
            get => _annotations ?? (_annotations = new InputMap<string>());
            set => _annotations = value;
        }

        [Input("configMapInfo")]
        public Input<StarRocksClusterSpecStarrocksfespecConfigmapinfoArgs>? ConfigMapInfo { get; set; }

        [Input("feEnvVars")]
        private InputList<StarRocksClusterSpecStarrocksfespecFeenvvarsArgs>? _feEnvVars;
        public InputList<StarRocksClusterSpecStarrocksfespecFeenvvarsArgs> FeEnvVars
        {
            get => _feEnvVars ?? (_feEnvVars = new InputList<StarRocksClusterSpecStarrocksfespecFeenvvarsArgs>());
            set => _feEnvVars = value;
        }

        [Input("fsGroup")]
        public Input<int>? FsGroup { get; set; }

        [Input("hostAliases")]
        private InputList<StarRocksClusterSpecStarrocksfespecHostaliasesArgs>? _hostAliases;
        public InputList<StarRocksClusterSpecStarrocksfespecHostaliasesArgs> HostAliases
        {
            get => _hostAliases ?? (_hostAliases = new InputList<StarRocksClusterSpecStarrocksfespecHostaliasesArgs>());
            set => _hostAliases = value;
        }

        [Input("image", required: true)]
        public Input<string> Image { get; set; } = null!;

        [Input("imagePullSecrets")]
        private InputList<StarRocksClusterSpecStarrocksfespecImagepullsecretsArgs>? _imagePullSecrets;
        public InputList<StarRocksClusterSpecStarrocksfespecImagepullsecretsArgs> ImagePullSecrets
        {
            get => _imagePullSecrets ?? (_imagePullSecrets = new InputList<StarRocksClusterSpecStarrocksfespecImagepullsecretsArgs>());
            set => _imagePullSecrets = value;
        }

        [Input("limits")]
        private InputMap<Union<int, string>>? _limits;
        public InputMap<Union<int, string>> Limits
        {
            get => _limits ?? (_limits = new InputMap<Union<int, string>>());
            set => _limits = value;
        }

        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("nodeSelector")]
        private InputMap<string>? _nodeSelector;
        public InputMap<string> NodeSelector
        {
            get => _nodeSelector ?? (_nodeSelector = new InputMap<string>());
            set => _nodeSelector = value;
        }

        [Input("podLabels")]
        private InputMap<string>? _podLabels;
        public InputMap<string> PodLabels
        {
            get => _podLabels ?? (_podLabels = new InputMap<string>());
            set => _podLabels = value;
        }

        [Input("probe")]
        public Input<StarRocksClusterSpecStarrocksfespecProbeArgs>? Probe { get; set; }

        [Input("replicas")]
        public Input<int>? Replicas { get; set; }

        [Input("requests")]
        private InputMap<Union<int, string>>? _requests;
        public InputMap<Union<int, string>> Requests
        {
            get => _requests ?? (_requests = new InputMap<Union<int, string>>());
            set => _requests = value;
        }

        [Input("service")]
        public Input<StarRocksClusterSpecStarrocksfespecServiceArgs>? Service { get; set; }

        [Input("serviceAccount")]
        public Input<string>? ServiceAccount { get; set; }

        [Input("storageVolumes")]
        private InputList<StarRocksClusterSpecStarrocksfespecStoragevolumesArgs>? _storageVolumes;
        public InputList<StarRocksClusterSpecStarrocksfespecStoragevolumesArgs> StorageVolumes
        {
            get => _storageVolumes ?? (_storageVolumes = new InputList<StarRocksClusterSpecStarrocksfespecStoragevolumesArgs>());
            set => _storageVolumes = value;
        }

        [Input("tolerations")]
        private InputList<StarRocksClusterSpecStarrocksfespecTolerationsArgs>? _tolerations;
        public InputList<StarRocksClusterSpecStarrocksfespecTolerationsArgs> Tolerations
        {
            get => _tolerations ?? (_tolerations = new InputList<StarRocksClusterSpecStarrocksfespecTolerationsArgs>());
            set => _tolerations = value;
        }

        public StarRocksClusterSpecStarrocksfespecArgs()
        {
        }
        public static new StarRocksClusterSpecStarrocksfespecArgs Empty => new StarRocksClusterSpecStarrocksfespecArgs();
    }
}
