// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using Pulumi;

namespace Unilake.Iac.Kubernetes.Custom.Crds.StarRock.V1Alpha1.Inputs
{

    public class StarRocksClusterSpecStarrockscnspecCnenvvarsValuefromConfigmapkeyrefArgs : global::Pulumi.ResourceArgs
    {
        [Input("key", required: true)]
        public Input<string> Key { get; set; } = null!;

        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("optional")]
        public Input<bool>? Optional { get; set; }

        public StarRocksClusterSpecStarrockscnspecCnenvvarsValuefromConfigmapkeyrefArgs()
        {
        }
        public static new StarRocksClusterSpecStarrockscnspecCnenvvarsValuefromConfigmapkeyrefArgs Empty => new StarRocksClusterSpecStarrockscnspecCnenvvarsValuefromConfigmapkeyrefArgs();
    }
}
