// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using Pulumi;

namespace Unilake.Iac.Kubernetes.Custom.Crds.StarRock.V1Alpha1.Inputs
{

    public class StarRocksClusterSpecStarrockscnspecAutoscalingpolicyHpapolicyBehaviorArgs : global::Pulumi.ResourceArgs
    {
        [Input("scaleDown")]
        public Input<StarRocksClusterSpecStarrockscnspecAutoscalingpolicyHpapolicyBehaviorScaledownArgs>? ScaleDown { get; set; }

        [Input("scaleUp")]
        public Input<StarRocksClusterSpecStarrockscnspecAutoscalingpolicyHpapolicyBehaviorScaleupArgs>? ScaleUp { get; set; }

        public StarRocksClusterSpecStarrockscnspecAutoscalingpolicyHpapolicyBehaviorArgs()
        {
        }
        public static new StarRocksClusterSpecStarrockscnspecAutoscalingpolicyHpapolicyBehaviorArgs Empty => new StarRocksClusterSpecStarrockscnspecAutoscalingpolicyHpapolicyBehaviorArgs();
    }
}
