// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using Pulumi;

namespace Unilake.Iac.Kubernetes.Custom.Crds.StarRock.V1Alpha1.Inputs
{

    public class StarRocksClusterSpecStarrockscnspecCnenvvarsValuefromArgs : global::Pulumi.ResourceArgs
    {
        [Input("configMapKeyRef")]
        public Input<StarRocksClusterSpecStarrockscnspecCnenvvarsValuefromConfigmapkeyrefArgs>? ConfigMapKeyRef { get; set; }

        [Input("fieldRef")]
        public Input<StarRocksClusterSpecStarrockscnspecCnenvvarsValuefromFieldrefArgs>? FieldRef { get; set; }

        [Input("resourceFieldRef")]
        public Input<StarRocksClusterSpecStarrockscnspecCnenvvarsValuefromResourcefieldrefArgs>? ResourceFieldRef { get; set; }

        [Input("secretKeyRef")]
        public Input<StarRocksClusterSpecStarrockscnspecCnenvvarsValuefromSecretkeyrefArgs>? SecretKeyRef { get; set; }

        public StarRocksClusterSpecStarrockscnspecCnenvvarsValuefromArgs()
        {
        }
        public static new StarRocksClusterSpecStarrockscnspecCnenvvarsValuefromArgs Empty => new StarRocksClusterSpecStarrockscnspecCnenvvarsValuefromArgs();
    }
}
