// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using Pulumi;

namespace Unilake.Iac.Kubernetes.Custom.Crds.StarRock.V1Alpha1.Inputs
{

    public class StarRocksClusterSpecStarrockscnspecAutoscalingpolicyHpapolicyBehaviorScaleupArgs : global::Pulumi.ResourceArgs
    {
        [Input("policies")]
        private InputList<StarRocksClusterSpecStarrockscnspecAutoscalingpolicyHpapolicyBehaviorScaleupPoliciesArgs>? _policies;
        public InputList<StarRocksClusterSpecStarrockscnspecAutoscalingpolicyHpapolicyBehaviorScaleupPoliciesArgs> Policies
        {
            get => _policies ?? (_policies = new InputList<StarRocksClusterSpecStarrockscnspecAutoscalingpolicyHpapolicyBehaviorScaleupPoliciesArgs>());
            set => _policies = value;
        }

        [Input("selectPolicy")]
        public Input<string>? SelectPolicy { get; set; }

        [Input("stabilizationWindowSeconds")]
        public Input<int>? StabilizationWindowSeconds { get; set; }

        public StarRocksClusterSpecStarrockscnspecAutoscalingpolicyHpapolicyBehaviorScaleupArgs()
        {
        }
        public static new StarRocksClusterSpecStarrockscnspecAutoscalingpolicyHpapolicyBehaviorScaleupArgs Empty => new StarRocksClusterSpecStarrockscnspecAutoscalingpolicyHpapolicyBehaviorScaleupArgs();
    }
}
