// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using Pulumi;

namespace Unilake.Iac.Kubernetes.Custom.Crds.StarRock.V1Alpha1.Inputs
{

    public class StarRocksClusterSpecStarrocksbespecAffinityNodeaffinityPreferredduringschedulingignoredduringexecutionArgs : global::Pulumi.ResourceArgs
    {
        [Input("preference", required: true)]
        public Input<StarRocksClusterSpecStarrocksbespecAffinityNodeaffinityPreferredduringschedulingignoredduringexecutionPreferenceArgs> Preference { get; set; } = null!;

        [Input("weight", required: true)]
        public Input<int> Weight { get; set; } = null!;

        public StarRocksClusterSpecStarrocksbespecAffinityNodeaffinityPreferredduringschedulingignoredduringexecutionArgs()
        {
        }
        public static new StarRocksClusterSpecStarrocksbespecAffinityNodeaffinityPreferredduringschedulingignoredduringexecutionArgs Empty => new StarRocksClusterSpecStarrocksbespecAffinityNodeaffinityPreferredduringschedulingignoredduringexecutionArgs();
    }
}
