// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using Pulumi;

namespace Unilake.Iac.Kubernetes.Custom.Crds.StarRock.V1Alpha1.Inputs
{

    public class StarRocksClusterSpecStarrockscnspecAutoscalingpolicyHpapolicyBehaviorScaledownArgs : global::Pulumi.ResourceArgs
    {
        [Input("policies")]
        private InputList<StarRocksClusterSpecStarrockscnspecAutoscalingpolicyHpapolicyBehaviorScaledownPoliciesArgs>? _policies;
        public InputList<StarRocksClusterSpecStarrockscnspecAutoscalingpolicyHpapolicyBehaviorScaledownPoliciesArgs> Policies
        {
            get => _policies ?? (_policies = new InputList<StarRocksClusterSpecStarrockscnspecAutoscalingpolicyHpapolicyBehaviorScaledownPoliciesArgs>());
            set => _policies = value;
        }

        [Input("selectPolicy")]
        public Input<string>? SelectPolicy { get; set; }

        [Input("stabilizationWindowSeconds")]
        public Input<int>? StabilizationWindowSeconds { get; set; }

        public StarRocksClusterSpecStarrockscnspecAutoscalingpolicyHpapolicyBehaviorScaledownArgs()
        {
        }
        public static new StarRocksClusterSpecStarrockscnspecAutoscalingpolicyHpapolicyBehaviorScaledownArgs Empty => new StarRocksClusterSpecStarrockscnspecAutoscalingpolicyHpapolicyBehaviorScaledownArgs();
    }
}
