// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using Pulumi;

namespace Unilake.Iac.Kubernetes.Custom.Crds.StarRock.V1Alpha1.Inputs
{

    public class StarRocksClusterSpecStarrockscnspecTolerationsArgs : global::Pulumi.ResourceArgs
    {
        [Input("effect")]
        public Input<string>? Effect { get; set; }

        [Input("key")]
        public Input<string>? Key { get; set; }

        [Input("operator")]
        public Input<string>? Operator { get; set; }

        [Input("tolerationSeconds")]
        public Input<int>? TolerationSeconds { get; set; }

        [Input("value")]
        public Input<string>? Value { get; set; }

        public StarRocksClusterSpecStarrockscnspecTolerationsArgs()
        {
        }
        public static new StarRocksClusterSpecStarrockscnspecTolerationsArgs Empty => new StarRocksClusterSpecStarrockscnspecTolerationsArgs();
    }
}
