// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using Pulumi;

namespace Unilake.Iac.Kubernetes.Custom.Crds.StarRock.V1Alpha1.Inputs
{

    public class StarRocksClusterSpecStarrockscnspecAutoscalingpolicyHpapolicyMetricsPodsArgs : global::Pulumi.ResourceArgs
    {
        [Input("metric", required: true)]
        public Input<StarRocksClusterSpecStarrockscnspecAutoscalingpolicyHpapolicyMetricsPodsMetricArgs> Metric { get; set; } = null!;

        [Input("target", required: true)]
        public Input<StarRocksClusterSpecStarrockscnspecAutoscalingpolicyHpapolicyMetricsPodsTargetArgs> Target { get; set; } = null!;

        public StarRocksClusterSpecStarrockscnspecAutoscalingpolicyHpapolicyMetricsPodsArgs()
        {
        }
        public static new StarRocksClusterSpecStarrockscnspecAutoscalingpolicyHpapolicyMetricsPodsArgs Empty => new StarRocksClusterSpecStarrockscnspecAutoscalingpolicyHpapolicyMetricsPodsArgs();
    }
}
