// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using Pulumi;

namespace Unilake.Iac.Kubernetes.Custom.Crds.StarRock.V1Alpha1.Inputs
{

    public class StarRocksClusterSpecStarrockscnspecAutoscalingpolicyHpapolicyMetricsContainerresourceArgs : global::Pulumi.ResourceArgs
    {
        [Input("container", required: true)]
        public Input<string> Container { get; set; } = null!;

        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        [Input("target", required: true)]
        public Input<StarRocksClusterSpecStarrockscnspecAutoscalingpolicyHpapolicyMetricsContainerresourceTargetArgs> Target { get; set; } = null!;

        public StarRocksClusterSpecStarrockscnspecAutoscalingpolicyHpapolicyMetricsContainerresourceArgs()
        {
        }
        public static new StarRocksClusterSpecStarrockscnspecAutoscalingpolicyHpapolicyMetricsContainerresourceArgs Empty => new StarRocksClusterSpecStarrockscnspecAutoscalingpolicyHpapolicyMetricsContainerresourceArgs();
    }
}
