// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using Pulumi;

namespace Unilake.Iac.Kubernetes.Custom.Crds.StarRock.V1Alpha1.Inputs
{

    public class StarRocksClusterSpecStarrockscnspecAutoscalingpolicyHpapolicyMetricsPodsMetricArgs : global::Pulumi.ResourceArgs
    {
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        [Input("selector")]
        public Input<StarRocksClusterSpecStarrockscnspecAutoscalingpolicyHpapolicyMetricsPodsMetricSelectorArgs>? Selector { get; set; }

        public StarRocksClusterSpecStarrockscnspecAutoscalingpolicyHpapolicyMetricsPodsMetricArgs()
        {
        }
        public static new StarRocksClusterSpecStarrockscnspecAutoscalingpolicyHpapolicyMetricsPodsMetricArgs Empty => new StarRocksClusterSpecStarrockscnspecAutoscalingpolicyHpapolicyMetricsPodsMetricArgs();
    }
}
