// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using Pulumi;

namespace Unilake.Iac.Kubernetes.Custom.Crds.StarRock.V1Alpha1.Inputs
{

    public class StarRocksClusterSpecStarrocksbespecArgs : global::Pulumi.ResourceArgs
    {
        [Input("affinity")]
        public Input<StarRocksClusterSpecStarrocksbespecAffinityArgs>? Affinity { get; set; }

        [Input("annotations")]
        private InputMap<string>? _annotations;
        public InputMap<string> Annotations
        {
            get => _annotations ?? (_annotations = new InputMap<string>());
            set => _annotations = value;
        }

        [Input("beEnvVars")]
        private InputList<StarRocksClusterSpecStarrocksbespecBeenvvarsArgs>? _beEnvVars;
        public InputList<StarRocksClusterSpecStarrocksbespecBeenvvarsArgs> BeEnvVars
        {
            get => _beEnvVars ?? (_beEnvVars = new InputList<StarRocksClusterSpecStarrocksbespecBeenvvarsArgs>());
            set => _beEnvVars = value;
        }

        [Input("configMapInfo")]
        public Input<StarRocksClusterSpecStarrocksbespecConfigmapinfoArgs>? ConfigMapInfo { get; set; }

        [Input("fsGroup")]
        public Input<int>? FsGroup { get; set; }

        [Input("hostAliases")]
        private InputList<StarRocksClusterSpecStarrocksbespecHostaliasesArgs>? _hostAliases;
        public InputList<StarRocksClusterSpecStarrocksbespecHostaliasesArgs> HostAliases
        {
            get => _hostAliases ?? (_hostAliases = new InputList<StarRocksClusterSpecStarrocksbespecHostaliasesArgs>());
            set => _hostAliases = value;
        }

        [Input("image", required: true)]
        public Input<string> Image { get; set; } = null!;

        [Input("imagePullSecrets")]
        private InputList<StarRocksClusterSpecStarrocksbespecImagepullsecretsArgs>? _imagePullSecrets;
        public InputList<StarRocksClusterSpecStarrocksbespecImagepullsecretsArgs> ImagePullSecrets
        {
            get => _imagePullSecrets ?? (_imagePullSecrets = new InputList<StarRocksClusterSpecStarrocksbespecImagepullsecretsArgs>());
            set => _imagePullSecrets = value;
        }

        [Input("limits")]
        private InputMap<Union<int, string>>? _limits;
        public InputMap<Union<int, string>> Limits
        {
            get => _limits ?? (_limits = new InputMap<Union<int, string>>());
            set => _limits = value;
        }

        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("nodeSelector")]
        private InputMap<string>? _nodeSelector;
        public InputMap<string> NodeSelector
        {
            get => _nodeSelector ?? (_nodeSelector = new InputMap<string>());
            set => _nodeSelector = value;
        }

        [Input("podLabels")]
        private InputMap<string>? _podLabels;
        public InputMap<string> PodLabels
        {
            get => _podLabels ?? (_podLabels = new InputMap<string>());
            set => _podLabels = value;
        }

        [Input("probe")]
        public Input<StarRocksClusterSpecStarrocksbespecProbeArgs>? Probe { get; set; }

        [Input("replicaInstances")]
        private InputList<string>? _replicaInstances;
        public InputList<string> ReplicaInstances
        {
            get => _replicaInstances ?? (_replicaInstances = new InputList<string>());
            set => _replicaInstances = value;
        }

        [Input("replicas")]
        public Input<int>? Replicas { get; set; }

        [Input("requests")]
        private InputMap<Union<int, string>>? _requests;
        public InputMap<Union<int, string>> Requests
        {
            get => _requests ?? (_requests = new InputMap<Union<int, string>>());
            set => _requests = value;
        }

        [Input("service")]
        public Input<StarRocksClusterSpecStarrocksbespecServiceArgs>? Service { get; set; }

        [Input("serviceAccount")]
        public Input<string>? ServiceAccount { get; set; }

        [Input("storageVolumes")]
        private InputList<StarRocksClusterSpecStarrocksbespecStoragevolumesArgs>? _storageVolumes;
        public InputList<StarRocksClusterSpecStarrocksbespecStoragevolumesArgs> StorageVolumes
        {
            get => _storageVolumes ?? (_storageVolumes = new InputList<StarRocksClusterSpecStarrocksbespecStoragevolumesArgs>());
            set => _storageVolumes = value;
        }

        [Input("tolerations")]
        private InputList<StarRocksClusterSpecStarrocksbespecTolerationsArgs>? _tolerations;
        public InputList<StarRocksClusterSpecStarrocksbespecTolerationsArgs> Tolerations
        {
            get => _tolerations ?? (_tolerations = new InputList<StarRocksClusterSpecStarrocksbespecTolerationsArgs>());
            set => _tolerations = value;
        }

        public StarRocksClusterSpecStarrocksbespecArgs()
        {
        }
        public static new StarRocksClusterSpecStarrocksbespecArgs Empty => new StarRocksClusterSpecStarrocksbespecArgs();
    }
}
