// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using Pulumi;

namespace Unilake.Iac.Kubernetes.Custom.Crds.StarRock.V1Alpha1.Inputs
{

    public class StarRocksClusterSpecStarrocksfespecAffinityNodeaffinityRequiredduringschedulingignoredduringexecutionArgs : global::Pulumi.ResourceArgs
    {
        [Input("nodeSelectorTerms", required: true)]
        private InputList<StarRocksClusterSpecStarrocksfespecAffinityNodeaffinityRequiredduringschedulingignoredduringexecutionNodeselectortermsArgs>? _nodeSelectorTerms;
        public InputList<StarRocksClusterSpecStarrocksfespecAffinityNodeaffinityRequiredduringschedulingignoredduringexecutionNodeselectortermsArgs> NodeSelectorTerms
        {
            get => _nodeSelectorTerms ?? (_nodeSelectorTerms = new InputList<StarRocksClusterSpecStarrocksfespecAffinityNodeaffinityRequiredduringschedulingignoredduringexecutionNodeselectortermsArgs>());
            set => _nodeSelectorTerms = value;
        }

        public StarRocksClusterSpecStarrocksfespecAffinityNodeaffinityRequiredduringschedulingignoredduringexecutionArgs()
        {
        }
        public static new StarRocksClusterSpecStarrocksfespecAffinityNodeaffinityRequiredduringschedulingignoredduringexecutionArgs Empty => new StarRocksClusterSpecStarrocksfespecAffinityNodeaffinityRequiredduringschedulingignoredduringexecutionArgs();
    }
}
