// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using Pulumi;

namespace Unilake.Iac.Kubernetes.Custom.Crds.StarRock.V1Alpha1.Inputs
{

    public class StarRocksClusterSpecStarrocksfespecServicePortsArgs : global::Pulumi.ResourceArgs
    {
        [Input("containerPort", required: true)]
        public Input<int> ContainerPort { get; set; } = null!;

        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("nodePort")]
        public Input<int>? NodePort { get; set; }

        [Input("port", required: true)]
        public Input<int> Port { get; set; } = null!;

        public StarRocksClusterSpecStarrocksfespecServicePortsArgs()
        {
        }
        public static new StarRocksClusterSpecStarrocksfespecServicePortsArgs Empty => new StarRocksClusterSpecStarrocksfespecServicePortsArgs();
    }
}
