// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using Pulumi;

namespace Unilake.Iac.Kubernetes.Custom.Crds.StarRock.V1Alpha1.Inputs
{

    public class StarRocksClusterSpecStarrocksfespecFeenvvarsValuefromArgs : global::Pulumi.ResourceArgs
    {
        [Input("configMapKeyRef")]
        public Input<StarRocksClusterSpecStarrocksfespecFeenvvarsValuefromConfigmapkeyrefArgs>? ConfigMapKeyRef { get; set; }

        [Input("fieldRef")]
        public Input<StarRocksClusterSpecStarrocksfespecFeenvvarsValuefromFieldrefArgs>? FieldRef { get; set; }

        [Input("resourceFieldRef")]
        public Input<StarRocksClusterSpecStarrocksfespecFeenvvarsValuefromResourcefieldrefArgs>? ResourceFieldRef { get; set; }

        [Input("secretKeyRef")]
        public Input<StarRocksClusterSpecStarrocksfespecFeenvvarsValuefromSecretkeyrefArgs>? SecretKeyRef { get; set; }

        public StarRocksClusterSpecStarrocksfespecFeenvvarsValuefromArgs()
        {
        }
        public static new StarRocksClusterSpecStarrocksfespecFeenvvarsValuefromArgs Empty => new StarRocksClusterSpecStarrocksfespecFeenvvarsValuefromArgs();
    }
}
