// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using Pulumi;

namespace Unilake.Iac.Kubernetes.Custom.Crds.StarRock.V1Alpha1.Inputs
{

    public class StarRocksClusterSpecStarrocksfespecAffinityNodeaffinityPreferredduringschedulingignoredduringexecutionPreferenceArgs : global::Pulumi.ResourceArgs
    {
        [Input("matchExpressions")]
        private InputList<StarRocksClusterSpecStarrocksfespecAffinityNodeaffinityPreferredduringschedulingignoredduringexecutionPreferenceMatchexpressionsArgs>? _matchExpressions;
        public InputList<StarRocksClusterSpecStarrocksfespecAffinityNodeaffinityPreferredduringschedulingignoredduringexecutionPreferenceMatchexpressionsArgs> MatchExpressions
        {
            get => _matchExpressions ?? (_matchExpressions = new InputList<StarRocksClusterSpecStarrocksfespecAffinityNodeaffinityPreferredduringschedulingignoredduringexecutionPreferenceMatchexpressionsArgs>());
            set => _matchExpressions = value;
        }

        [Input("matchFields")]
        private InputList<StarRocksClusterSpecStarrocksfespecAffinityNodeaffinityPreferredduringschedulingignoredduringexecutionPreferenceMatchfieldsArgs>? _matchFields;
        public InputList<StarRocksClusterSpecStarrocksfespecAffinityNodeaffinityPreferredduringschedulingignoredduringexecutionPreferenceMatchfieldsArgs> MatchFields
        {
            get => _matchFields ?? (_matchFields = new InputList<StarRocksClusterSpecStarrocksfespecAffinityNodeaffinityPreferredduringschedulingignoredduringexecutionPreferenceMatchfieldsArgs>());
            set => _matchFields = value;
        }

        public StarRocksClusterSpecStarrocksfespecAffinityNodeaffinityPreferredduringschedulingignoredduringexecutionPreferenceArgs()
        {
        }
        public static new StarRocksClusterSpecStarrocksfespecAffinityNodeaffinityPreferredduringschedulingignoredduringexecutionPreferenceArgs Empty => new StarRocksClusterSpecStarrocksfespecAffinityNodeaffinityPreferredduringschedulingignoredduringexecutionPreferenceArgs();
    }
}
