// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using Pulumi;

namespace Unilake.Iac.Kubernetes.Custom.Crds.StarRock.V1Alpha1.Inputs
{

    public class StarRocksClusterSpecStarrocksfespecAffinityNodeaffinityRequiredduringschedulingignoredduringexecutionNodeselectortermsArgs : global::Pulumi.ResourceArgs
    {
        [Input("matchExpressions")]
        private InputList<StarRocksClusterSpecStarrocksfespecAffinityNodeaffinityRequiredduringschedulingignoredduringexecutionNodeselectortermsMatchexpressionsArgs>? _matchExpressions;
        public InputList<StarRocksClusterSpecStarrocksfespecAffinityNodeaffinityRequiredduringschedulingignoredduringexecutionNodeselectortermsMatchexpressionsArgs> MatchExpressions
        {
            get => _matchExpressions ?? (_matchExpressions = new InputList<StarRocksClusterSpecStarrocksfespecAffinityNodeaffinityRequiredduringschedulingignoredduringexecutionNodeselectortermsMatchexpressionsArgs>());
            set => _matchExpressions = value;
        }

        [Input("matchFields")]
        private InputList<StarRocksClusterSpecStarrocksfespecAffinityNodeaffinityRequiredduringschedulingignoredduringexecutionNodeselectortermsMatchfieldsArgs>? _matchFields;
        public InputList<StarRocksClusterSpecStarrocksfespecAffinityNodeaffinityRequiredduringschedulingignoredduringexecutionNodeselectortermsMatchfieldsArgs> MatchFields
        {
            get => _matchFields ?? (_matchFields = new InputList<StarRocksClusterSpecStarrocksfespecAffinityNodeaffinityRequiredduringschedulingignoredduringexecutionNodeselectortermsMatchfieldsArgs>());
            set => _matchFields = value;
        }

        public StarRocksClusterSpecStarrocksfespecAffinityNodeaffinityRequiredduringschedulingignoredduringexecutionNodeselectortermsArgs()
        {
        }
        public static new StarRocksClusterSpecStarrocksfespecAffinityNodeaffinityRequiredduringschedulingignoredduringexecutionNodeselectortermsArgs Empty => new StarRocksClusterSpecStarrocksfespecAffinityNodeaffinityRequiredduringschedulingignoredduringexecutionNodeselectortermsArgs();
    }
}
