// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using Pulumi;

namespace Unilake.Iac.Kubernetes.Custom.Crds.StarRock.V1Alpha1.Inputs
{

    public class StarRocksClusterSpecStarrocksbespecServiceArgs : global::Pulumi.ResourceArgs
    {
        [Input("loadBalancerIP")]
        public Input<string>? LoadBalancerIP { get; set; }

        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("ports")]
        private InputList<StarRocksClusterSpecStarrocksbespecServicePortsArgs>? _ports;
        public InputList<StarRocksClusterSpecStarrocksbespecServicePortsArgs> Ports
        {
            get => _ports ?? (_ports = new InputList<StarRocksClusterSpecStarrocksbespecServicePortsArgs>());
            set => _ports = value;
        }

        [Input("type")]
        public Input<string>? Type { get; set; }

        public StarRocksClusterSpecStarrocksbespecServiceArgs()
        {
        }
        public static new StarRocksClusterSpecStarrocksbespecServiceArgs Empty => new StarRocksClusterSpecStarrocksbespecServiceArgs();
    }
}
