// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using Pulumi;

namespace Unilake.Iac.Kubernetes.Custom.Crds.StarRock.V1Alpha1.Inputs
{

    public class StarRocksClusterSpecStarrockscnspecAutoscalingpolicyHpapolicyArgs : global::Pulumi.ResourceArgs
    {
        [Input("behavior")]
        public Input<StarRocksClusterSpecStarrockscnspecAutoscalingpolicyHpapolicyBehaviorArgs>? Behavior { get; set; }

        [Input("metrics")]
        private InputList<StarRocksClusterSpecStarrockscnspecAutoscalingpolicyHpapolicyMetricsArgs>? _metrics;
        public InputList<StarRocksClusterSpecStarrockscnspecAutoscalingpolicyHpapolicyMetricsArgs> Metrics
        {
            get => _metrics ?? (_metrics = new InputList<StarRocksClusterSpecStarrockscnspecAutoscalingpolicyHpapolicyMetricsArgs>());
            set => _metrics = value;
        }

        public StarRocksClusterSpecStarrockscnspecAutoscalingpolicyHpapolicyArgs()
        {
        }
        public static new StarRocksClusterSpecStarrockscnspecAutoscalingpolicyHpapolicyArgs Empty => new StarRocksClusterSpecStarrockscnspecAutoscalingpolicyHpapolicyArgs();
    }
}
