// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using Pulumi;

namespace Unilake.Iac.Kubernetes.Custom.Crds.StarRock.V1Alpha1.Inputs
{

    public class StarRocksClusterSpecStarrockscnspecArgs : global::Pulumi.ResourceArgs
    {
        [Input("affinity")]
        public Input<StarRocksClusterSpecStarrockscnspecAffinityArgs>? Affinity { get; set; }

        [Input("annotations")]
        private InputMap<string>? _annotations;
        public InputMap<string> Annotations
        {
            get => _annotations ?? (_annotations = new InputMap<string>());
            set => _annotations = value;
        }

        [Input("autoScalingPolicy")]
        public Input<StarRocksClusterSpecStarrockscnspecAutoscalingpolicyArgs>? AutoScalingPolicy { get; set; }

        [Input("cnEnvVars")]
        private InputList<StarRocksClusterSpecStarrockscnspecCnenvvarsArgs>? _cnEnvVars;
        public InputList<StarRocksClusterSpecStarrockscnspecCnenvvarsArgs> CnEnvVars
        {
            get => _cnEnvVars ?? (_cnEnvVars = new InputList<StarRocksClusterSpecStarrockscnspecCnenvvarsArgs>());
            set => _cnEnvVars = value;
        }

        [Input("configMapInfo")]
        public Input<StarRocksClusterSpecStarrockscnspecConfigmapinfoArgs>? ConfigMapInfo { get; set; }

        [Input("fsGroup")]
        public Input<int>? FsGroup { get; set; }

        [Input("hostAliases")]
        private InputList<StarRocksClusterSpecStarrockscnspecHostaliasesArgs>? _hostAliases;
        public InputList<StarRocksClusterSpecStarrockscnspecHostaliasesArgs> HostAliases
        {
            get => _hostAliases ?? (_hostAliases = new InputList<StarRocksClusterSpecStarrockscnspecHostaliasesArgs>());
            set => _hostAliases = value;
        }

        [Input("image", required: true)]
        public Input<string> Image { get; set; } = null!;

        [Input("imagePullSecrets")]
        private InputList<StarRocksClusterSpecStarrockscnspecImagepullsecretsArgs>? _imagePullSecrets;
        public InputList<StarRocksClusterSpecStarrockscnspecImagepullsecretsArgs> ImagePullSecrets
        {
            get => _imagePullSecrets ?? (_imagePullSecrets = new InputList<StarRocksClusterSpecStarrockscnspecImagepullsecretsArgs>());
            set => _imagePullSecrets = value;
        }

        [Input("limits")]
        private InputMap<Union<int, string>>? _limits;
        public InputMap<Union<int, string>> Limits
        {
            get => _limits ?? (_limits = new InputMap<Union<int, string>>());
            set => _limits = value;
        }

        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("nodeSelector")]
        private InputMap<string>? _nodeSelector;
        public InputMap<string> NodeSelector
        {
            get => _nodeSelector ?? (_nodeSelector = new InputMap<string>());
            set => _nodeSelector = value;
        }

        [Input("podLabels")]
        private InputMap<string>? _podLabels;
        public InputMap<string> PodLabels
        {
            get => _podLabels ?? (_podLabels = new InputMap<string>());
            set => _podLabels = value;
        }

        [Input("probe")]
        public Input<StarRocksClusterSpecStarrockscnspecProbeArgs>? Probe { get; set; }

        [Input("replicas")]
        public Input<int>? Replicas { get; set; }

        [Input("requests")]
        private InputMap<Union<int, string>>? _requests;
        public InputMap<Union<int, string>> Requests
        {
            get => _requests ?? (_requests = new InputMap<Union<int, string>>());
            set => _requests = value;
        }

        [Input("service")]
        public Input<StarRocksClusterSpecStarrockscnspecServiceArgs>? Service { get; set; }

        [Input("serviceAccount")]
        public Input<string>? ServiceAccount { get; set; }

        [Input("tolerations")]
        private InputList<StarRocksClusterSpecStarrockscnspecTolerationsArgs>? _tolerations;
        public InputList<StarRocksClusterSpecStarrockscnspecTolerationsArgs> Tolerations
        {
            get => _tolerations ?? (_tolerations = new InputList<StarRocksClusterSpecStarrockscnspecTolerationsArgs>());
            set => _tolerations = value;
        }

        public StarRocksClusterSpecStarrockscnspecArgs()
        {
        }
        public static new StarRocksClusterSpecStarrockscnspecArgs Empty => new StarRocksClusterSpecStarrockscnspecArgs();
    }
}
