// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using Pulumi;

namespace Unilake.Iac.Kubernetes.Custom.Crds.StarRock.V1Alpha1.Inputs
{

    public class StarRocksClusterSpecStarrocksbespecAffinityArgs : global::Pulumi.ResourceArgs
    {
        [Input("nodeAffinity")]
        public Input<StarRocksClusterSpecStarrocksbespecAffinityNodeaffinityArgs>? NodeAffinity { get; set; }

        [Input("podAffinity")]
        public Input<StarRocksClusterSpecStarrocksbespecAffinityPodaffinityArgs>? PodAffinity { get; set; }

        [Input("podAntiAffinity")]
        public Input<StarRocksClusterSpecStarrocksbespecAffinityPodantiaffinityArgs>? PodAntiAffinity { get; set; }

        public StarRocksClusterSpecStarrocksbespecAffinityArgs()
        {
        }
        public static new StarRocksClusterSpecStarrocksbespecAffinityArgs Empty => new StarRocksClusterSpecStarrocksbespecAffinityArgs();
    }
}
