// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using Pulumi;

namespace Unilake.Iac.Kubernetes.Custom.Crds.StarRock.V1Alpha1.Inputs
{

    public class StarRocksClusterSpecStarrocksfespecFeenvvarsValuefromResourcefieldrefArgs : global::Pulumi.ResourceArgs
    {
        [Input("containerName")]
        public Input<string>? ContainerName { get; set; }

        [Input("divisor")]
        public InputUnion<int, string>? Divisor { get; set; }

        [Input("resource", required: true)]
        public Input<string> Resource { get; set; } = null!;

        public StarRocksClusterSpecStarrocksfespecFeenvvarsValuefromResourcefieldrefArgs()
        {
        }
        public static new StarRocksClusterSpecStarrocksfespecFeenvvarsValuefromResourcefieldrefArgs Empty => new StarRocksClusterSpecStarrocksfespecFeenvvarsValuefromResourcefieldrefArgs();
    }
}
