// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using Pulumi;

namespace Unilake.Iac.Kubernetes.Custom.Crds.StarRock.V1Alpha1.Inputs
{

    public class StarRocksClusterSpecStarrocksfespecProbeArgs : global::Pulumi.ResourceArgs
    {
        [Input("initialDelaySeconds")]
        public Input<int>? InitialDelaySeconds { get; set; }

        [Input("periodSeconds")]
        public Input<int>? PeriodSeconds { get; set; }

        [Input("type", required: true)]
        public Input<string> Type { get; set; } = null!;

        public StarRocksClusterSpecStarrocksfespecProbeArgs()
        {
        }
        public static new StarRocksClusterSpecStarrocksfespecProbeArgs Empty => new StarRocksClusterSpecStarrocksfespecProbeArgs();
    }
}
