// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using Pulumi;

namespace Unilake.Iac.Kubernetes.Custom.Crds.StarRock.V1Alpha1.Inputs
{

    public class StarRocksClusterSpecStarrocksbespecAffinityNodeaffinityRequiredduringschedulingignoredduringexecutionArgs : global::Pulumi.ResourceArgs
    {
        [Input("nodeSelectorTerms", required: true)]
        private InputList<StarRocksClusterSpecStarrocksbespecAffinityNodeaffinityRequiredduringschedulingignoredduringexecutionNodeselectortermsArgs>? _nodeSelectorTerms;
        public InputList<StarRocksClusterSpecStarrocksbespecAffinityNodeaffinityRequiredduringschedulingignoredduringexecutionNodeselectortermsArgs> NodeSelectorTerms
        {
            get => _nodeSelectorTerms ?? (_nodeSelectorTerms = new InputList<StarRocksClusterSpecStarrocksbespecAffinityNodeaffinityRequiredduringschedulingignoredduringexecutionNodeselectortermsArgs>());
            set => _nodeSelectorTerms = value;
        }

        public StarRocksClusterSpecStarrocksbespecAffinityNodeaffinityRequiredduringschedulingignoredduringexecutionArgs()
        {
        }
        public static new StarRocksClusterSpecStarrocksbespecAffinityNodeaffinityRequiredduringschedulingignoredduringexecutionArgs Empty => new StarRocksClusterSpecStarrocksbespecAffinityNodeaffinityRequiredduringschedulingignoredduringexecutionArgs();
    }
}
