// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using Pulumi;

namespace Unilake.Iac.Kubernetes.Custom.Crds.StarRock.V1Alpha1.Inputs
{

    public class StarRocksClusterStatusArgs : global::Pulumi.ResourceArgs
    {
        [Input("phase", required: true)]
        public Input<string> Phase { get; set; } = null!;

        [Input("starRocksBeStatus")]
        public Input<StarRocksClusterStatusStarrocksbestatusArgs>? StarRocksBeStatus { get; set; }

        [Input("starRocksCnStatus")]
        public Input<StarRocksClusterStatusStarrockscnstatusArgs>? StarRocksCnStatus { get; set; }

        [Input("starRocksFeStatus")]
        public Input<StarRocksClusterStatusStarrocksfestatusArgs>? StarRocksFeStatus { get; set; }

        public StarRocksClusterStatusArgs()
        {
        }
        public static new StarRocksClusterStatusArgs Empty => new StarRocksClusterStatusArgs();
    }
}
