// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using Pulumi;

namespace Unilake.Iac.Kubernetes.Custom.Crds.StarRock.V1Alpha1.Inputs
{

    public class StarRocksClusterSpecStarrockscnspecAutoscalingpolicyHpapolicyMetricsExternalArgs : global::Pulumi.ResourceArgs
    {
        [Input("metric", required: true)]
        public Input<StarRocksClusterSpecStarrockscnspecAutoscalingpolicyHpapolicyMetricsExternalMetricArgs> Metric { get; set; } = null!;

        [Input("target", required: true)]
        public Input<StarRocksClusterSpecStarrockscnspecAutoscalingpolicyHpapolicyMetricsExternalTargetArgs> Target { get; set; } = null!;

        public StarRocksClusterSpecStarrockscnspecAutoscalingpolicyHpapolicyMetricsExternalArgs()
        {
        }
        public static new StarRocksClusterSpecStarrockscnspecAutoscalingpolicyHpapolicyMetricsExternalArgs Empty => new StarRocksClusterSpecStarrockscnspecAutoscalingpolicyHpapolicyMetricsExternalArgs();
    }
}
