// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using Pulumi;

namespace Unilake.Iac.Kubernetes.Custom.Crds.StarRock.V1Alpha1.Inputs
{

    public class StarRocksClusterSpecStarrocksbespecAffinityPodaffinityArgs : global::Pulumi.ResourceArgs
    {
        [Input("preferredDuringSchedulingIgnoredDuringExecution")]
        private InputList<StarRocksClusterSpecStarrocksbespecAffinityPodaffinityPreferredduringschedulingignoredduringexecutionArgs>? _preferredDuringSchedulingIgnoredDuringExecution;
        public InputList<StarRocksClusterSpecStarrocksbespecAffinityPodaffinityPreferredduringschedulingignoredduringexecutionArgs> PreferredDuringSchedulingIgnoredDuringExecution
        {
            get => _preferredDuringSchedulingIgnoredDuringExecution ?? (_preferredDuringSchedulingIgnoredDuringExecution = new InputList<StarRocksClusterSpecStarrocksbespecAffinityPodaffinityPreferredduringschedulingignoredduringexecutionArgs>());
            set => _preferredDuringSchedulingIgnoredDuringExecution = value;
        }

        [Input("requiredDuringSchedulingIgnoredDuringExecution")]
        private InputList<StarRocksClusterSpecStarrocksbespecAffinityPodaffinityRequiredduringschedulingignoredduringexecutionArgs>? _requiredDuringSchedulingIgnoredDuringExecution;
        public InputList<StarRocksClusterSpecStarrocksbespecAffinityPodaffinityRequiredduringschedulingignoredduringexecutionArgs> RequiredDuringSchedulingIgnoredDuringExecution
        {
            get => _requiredDuringSchedulingIgnoredDuringExecution ?? (_requiredDuringSchedulingIgnoredDuringExecution = new InputList<StarRocksClusterSpecStarrocksbespecAffinityPodaffinityRequiredduringschedulingignoredduringexecutionArgs>());
            set => _requiredDuringSchedulingIgnoredDuringExecution = value;
        }

        public StarRocksClusterSpecStarrocksbespecAffinityPodaffinityArgs()
        {
        }
        public static new StarRocksClusterSpecStarrocksbespecAffinityPodaffinityArgs Empty => new StarRocksClusterSpecStarrocksbespecAffinityPodaffinityArgs();
    }
}
