// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using Pulumi;

namespace Unilake.Iac.Kubernetes.Custom.Crds.StarRock.V1Alpha1.Inputs
{

    public class StarRocksClusterSpecStarrockscnspecAutoscalingpolicyHpapolicyBehaviorScaleupPoliciesArgs : global::Pulumi.ResourceArgs
    {
        [Input("periodSeconds", required: true)]
        public Input<int> PeriodSeconds { get; set; } = null!;

        [Input("type", required: true)]
        public Input<string> Type { get; set; } = null!;

        [Input("value", required: true)]
        public Input<int> Value { get; set; } = null!;

        public StarRocksClusterSpecStarrockscnspecAutoscalingpolicyHpapolicyBehaviorScaleupPoliciesArgs()
        {
        }
        public static new StarRocksClusterSpecStarrockscnspecAutoscalingpolicyHpapolicyBehaviorScaleupPoliciesArgs Empty => new StarRocksClusterSpecStarrockscnspecAutoscalingpolicyHpapolicyBehaviorScaleupPoliciesArgs();
    }
}
