// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using Pulumi;

namespace Unilake.Iac.Kubernetes.Custom.Crds.StarRock.V1Alpha1.Inputs
{

    public class StarRocksClusterSpecArgs : global::Pulumi.ResourceArgs
    {
        [Input("serviceAccount")]
        public Input<string>? ServiceAccount { get; set; }

        [Input("starRocksBeSpec")]
        public Input<StarRocksClusterSpecStarrocksbespecArgs>? StarRocksBeSpec { get; set; }

        [Input("starRocksCnSpec")]
        public Input<StarRocksClusterSpecStarrockscnspecArgs>? StarRocksCnSpec { get; set; }

        [Input("starRocksFeSpec")]
        public Input<StarRocksClusterSpecStarrocksfespecArgs>? StarRocksFeSpec { get; set; }

        public StarRocksClusterSpecArgs()
        {
        }
        public static new StarRocksClusterSpecArgs Empty => new StarRocksClusterSpecArgs();
    }
}
