// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using Pulumi;

namespace Unilake.Iac.Kubernetes.Custom.Crds.StarRock.V1Alpha1.Inputs
{

    public class StarRocksClusterSpecStarrockscnspecImagepullsecretsArgs : global::Pulumi.ResourceArgs
    {
        [Input("name")]
        public Input<string>? Name { get; set; }

        public StarRocksClusterSpecStarrockscnspecImagepullsecretsArgs()
        {
        }
        public static new StarRocksClusterSpecStarrockscnspecImagepullsecretsArgs Empty => new StarRocksClusterSpecStarrockscnspecImagepullsecretsArgs();
    }
}
