// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using Pulumi;

namespace Unilake.Iac.Kubernetes.Custom.Crds.StarRock.V1Alpha1.Inputs
{

    public class StarRocksClusterSpecStarrocksbespecBeenvvarsValuefromArgs : global::Pulumi.ResourceArgs
    {
        [Input("configMapKeyRef")]
        public Input<StarRocksClusterSpecStarrocksbespecBeenvvarsValuefromConfigmapkeyrefArgs>? ConfigMapKeyRef { get; set; }

        [Input("fieldRef")]
        public Input<StarRocksClusterSpecStarrocksbespecBeenvvarsValuefromFieldrefArgs>? FieldRef { get; set; }

        [Input("resourceFieldRef")]
        public Input<StarRocksClusterSpecStarrocksbespecBeenvvarsValuefromResourcefieldrefArgs>? ResourceFieldRef { get; set; }

        [Input("secretKeyRef")]
        public Input<StarRocksClusterSpecStarrocksbespecBeenvvarsValuefromSecretkeyrefArgs>? SecretKeyRef { get; set; }

        public StarRocksClusterSpecStarrocksbespecBeenvvarsValuefromArgs()
        {
        }
        public static new StarRocksClusterSpecStarrocksbespecBeenvvarsValuefromArgs Empty => new StarRocksClusterSpecStarrocksbespecBeenvvarsValuefromArgs();
    }
}
