// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using Pulumi;

namespace Unilake.Iac.Kubernetes.Custom.Crds.StarRock.V1Alpha1.Inputs
{

    public class StarRocksClusterSpecStarrocksfespecAffinityArgs : global::Pulumi.ResourceArgs
    {
        [Input("nodeAffinity")]
        public Input<StarRocksClusterSpecStarrocksfespecAffinityNodeaffinityArgs>? NodeAffinity { get; set; }

        [Input("podAffinity")]
        public Input<StarRocksClusterSpecStarrocksfespecAffinityPodaffinityArgs>? PodAffinity { get; set; }

        [Input("podAntiAffinity")]
        public Input<StarRocksClusterSpecStarrocksfespecAffinityPodantiaffinityArgs>? PodAntiAffinity { get; set; }

        public StarRocksClusterSpecStarrocksfespecAffinityArgs()
        {
        }
        public static new StarRocksClusterSpecStarrocksfespecAffinityArgs Empty => new StarRocksClusterSpecStarrocksfespecAffinityArgs();
    }
}
