// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using Pulumi;

namespace Unilake.Iac.Kubernetes.Custom.Crds.StarRock.V1Alpha1.Inputs
{

    public class StarRocksClusterSpecStarrockscnspecAffinityPodaffinityRequiredduringschedulingignoredduringexecutionArgs : global::Pulumi.ResourceArgs
    {
        [Input("labelSelector")]
        public Input<StarRocksClusterSpecStarrockscnspecAffinityPodaffinityRequiredduringschedulingignoredduringexecutionLabelselectorArgs>? LabelSelector { get; set; }

        [Input("namespaceSelector")]
        public Input<StarRocksClusterSpecStarrockscnspecAffinityPodaffinityRequiredduringschedulingignoredduringexecutionNamespaceselectorArgs>? NamespaceSelector { get; set; }

        [Input("namespaces")]
        private InputList<string>? _namespaces;
        public InputList<string> Namespaces
        {
            get => _namespaces ?? (_namespaces = new InputList<string>());
            set => _namespaces = value;
        }

        [Input("topologyKey", required: true)]
        public Input<string> TopologyKey { get; set; } = null!;

        public StarRocksClusterSpecStarrockscnspecAffinityPodaffinityRequiredduringschedulingignoredduringexecutionArgs()
        {
        }
        public static new StarRocksClusterSpecStarrockscnspecAffinityPodaffinityRequiredduringschedulingignoredduringexecutionArgs Empty => new StarRocksClusterSpecStarrockscnspecAffinityPodaffinityRequiredduringschedulingignoredduringexecutionArgs();
    }
}
