// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using Pulumi;

namespace Unilake.Iac.Kubernetes.Custom.Crds.StarRock.V1Alpha1.Inputs
{

    public class StarRocksClusterSpecStarrocksfespecFeenvvarsArgs : global::Pulumi.ResourceArgs
    {
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        [Input("value")]
        public Input<string>? Value { get; set; }

        [Input("valueFrom")]
        public Input<StarRocksClusterSpecStarrocksfespecFeenvvarsValuefromArgs>? ValueFrom { get; set; }

        public StarRocksClusterSpecStarrocksfespecFeenvvarsArgs()
        {
        }
        public static new StarRocksClusterSpecStarrocksfespecFeenvvarsArgs Empty => new StarRocksClusterSpecStarrocksfespecFeenvvarsArgs();
    }
}
