// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using Pulumi;

namespace Unilake.Iac.Kubernetes.Custom.Crds.StarRock.V1Alpha1.Inputs
{

    public class StarRocksClusterSpecStarrocksbespecAffinityNodeaffinityPreferredduringschedulingignoredduringexecutionPreferenceArgs : global::Pulumi.ResourceArgs
    {
        [Input("matchExpressions")]
        private InputList<StarRocksClusterSpecStarrocksbespecAffinityNodeaffinityPreferredduringschedulingignoredduringexecutionPreferenceMatchexpressionsArgs>? _matchExpressions;
        public InputList<StarRocksClusterSpecStarrocksbespecAffinityNodeaffinityPreferredduringschedulingignoredduringexecutionPreferenceMatchexpressionsArgs> MatchExpressions
        {
            get => _matchExpressions ?? (_matchExpressions = new InputList<StarRocksClusterSpecStarrocksbespecAffinityNodeaffinityPreferredduringschedulingignoredduringexecutionPreferenceMatchexpressionsArgs>());
            set => _matchExpressions = value;
        }

        [Input("matchFields")]
        private InputList<StarRocksClusterSpecStarrocksbespecAffinityNodeaffinityPreferredduringschedulingignoredduringexecutionPreferenceMatchfieldsArgs>? _matchFields;
        public InputList<StarRocksClusterSpecStarrocksbespecAffinityNodeaffinityPreferredduringschedulingignoredduringexecutionPreferenceMatchfieldsArgs> MatchFields
        {
            get => _matchFields ?? (_matchFields = new InputList<StarRocksClusterSpecStarrocksbespecAffinityNodeaffinityPreferredduringschedulingignoredduringexecutionPreferenceMatchfieldsArgs>());
            set => _matchFields = value;
        }

        public StarRocksClusterSpecStarrocksbespecAffinityNodeaffinityPreferredduringschedulingignoredduringexecutionPreferenceArgs()
        {
        }
        public static new StarRocksClusterSpecStarrocksbespecAffinityNodeaffinityPreferredduringschedulingignoredduringexecutionPreferenceArgs Empty => new StarRocksClusterSpecStarrocksbespecAffinityNodeaffinityPreferredduringschedulingignoredduringexecutionPreferenceArgs();
    }
}
