// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using Pulumi;

namespace Unilake.Iac.Kubernetes.Custom.Crds.StarRock.V1Alpha1.Inputs
{

    public class StarRocksClusterSpecStarrocksbespecBeenvvarsValuefromFieldrefArgs : global::Pulumi.ResourceArgs
    {
        [Input("apiVersion")]
        public Input<string>? ApiVersion { get; set; }

        [Input("fieldPath", required: true)]
        public Input<string> FieldPath { get; set; } = null!;

        public StarRocksClusterSpecStarrocksbespecBeenvvarsValuefromFieldrefArgs()
        {
        }
        public static new StarRocksClusterSpecStarrocksbespecBeenvvarsValuefromFieldrefArgs Empty => new StarRocksClusterSpecStarrocksbespecBeenvvarsValuefromFieldrefArgs();
    }
}
