// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using Pulumi;

namespace Unilake.Iac.Kubernetes.Custom.Crds.StarRock.V1Alpha1.Inputs
{

    public class StarRocksClusterSpecStarrockscnspecAutoscalingpolicyHpapolicyMetricsArgs : global::Pulumi.ResourceArgs
    {
        [Input("containerResource")]
        public Input<StarRocksClusterSpecStarrockscnspecAutoscalingpolicyHpapolicyMetricsContainerresourceArgs>? ContainerResource { get; set; }

        [Input("external")]
        public Input<StarRocksClusterSpecStarrockscnspecAutoscalingpolicyHpapolicyMetricsExternalArgs>? External { get; set; }

        [Input("object")]
        public Input<StarRocksClusterSpecStarrockscnspecAutoscalingpolicyHpapolicyMetricsObjectArgs>? Object { get; set; }

        [Input("pods")]
        public Input<StarRocksClusterSpecStarrockscnspecAutoscalingpolicyHpapolicyMetricsPodsArgs>? Pods { get; set; }

        [Input("resource")]
        public Input<StarRocksClusterSpecStarrockscnspecAutoscalingpolicyHpapolicyMetricsResourceArgs>? Resource { get; set; }

        [Input("type", required: true)]
        public Input<string> Type { get; set; } = null!;

        public StarRocksClusterSpecStarrockscnspecAutoscalingpolicyHpapolicyMetricsArgs()
        {
        }
        public static new StarRocksClusterSpecStarrockscnspecAutoscalingpolicyHpapolicyMetricsArgs Empty => new StarRocksClusterSpecStarrockscnspecAutoscalingpolicyHpapolicyMetricsArgs();
    }
}
