// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using Pulumi;

namespace Unilake.Iac.Kubernetes.Custom.Crds.StarRock.V1Alpha1.Inputs
{

    public class StarRocksClusterSpecStarrockscnspecAutoscalingpolicyHpapolicyMetricsObjectTargetArgs : global::Pulumi.ResourceArgs
    {
        [Input("averageUtilization")]
        public Input<int>? AverageUtilization { get; set; }

        [Input("averageValue")]
        public InputUnion<int, string>? AverageValue { get; set; }

        [Input("type", required: true)]
        public Input<string> Type { get; set; } = null!;

        [Input("value")]
        public InputUnion<int, string>? Value { get; set; }

        public StarRocksClusterSpecStarrockscnspecAutoscalingpolicyHpapolicyMetricsObjectTargetArgs()
        {
        }
        public static new StarRocksClusterSpecStarrockscnspecAutoscalingpolicyHpapolicyMetricsObjectTargetArgs Empty => new StarRocksClusterSpecStarrockscnspecAutoscalingpolicyHpapolicyMetricsObjectTargetArgs();
    }
}
