// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using Pulumi;

namespace Unilake.Iac.Kubernetes.Custom.Crds.StarRock.V1Alpha1.Inputs
{

    public class StarRocksClusterSpecStarrockscnspecAffinityArgs : global::Pulumi.ResourceArgs
    {
        [Input("nodeAffinity")]
        public Input<StarRocksClusterSpecStarrockscnspecAffinityNodeaffinityArgs>? NodeAffinity { get; set; }

        [Input("podAffinity")]
        public Input<StarRocksClusterSpecStarrockscnspecAffinityPodaffinityArgs>? PodAffinity { get; set; }

        [Input("podAntiAffinity")]
        public Input<StarRocksClusterSpecStarrockscnspecAffinityPodantiaffinityArgs>? PodAntiAffinity { get; set; }

        public StarRocksClusterSpecStarrockscnspecAffinityArgs()
        {
        }
        public static new StarRocksClusterSpecStarrockscnspecAffinityArgs Empty => new StarRocksClusterSpecStarrockscnspecAffinityArgs();
    }
}
