// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using Pulumi;

namespace Unilake.Iac.Kubernetes.Custom.Crds.StarRock.V1Alpha1.Inputs
{

    public class StarRocksClusterSpecStarrocksbespecStoragevolumesArgs : global::Pulumi.ResourceArgs
    {
        [Input("mountPath")]
        public Input<string>? MountPath { get; set; }

        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        [Input("storageClassName")]
        public Input<string>? StorageClassName { get; set; }

        [Input("storageSize", required: true)]
        public Input<string> StorageSize { get; set; } = null!;

        public StarRocksClusterSpecStarrocksbespecStoragevolumesArgs()
        {
        }
        public static new StarRocksClusterSpecStarrocksbespecStoragevolumesArgs Empty => new StarRocksClusterSpecStarrocksbespecStoragevolumesArgs();
    }
}
