// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using Pulumi;

namespace Unilake.Iac.Kubernetes.Custom.Crds.StarRock.V1Alpha1.Inputs
{

    public class StarRocksClusterSpecStarrockscnspecConfigmapinfoArgs : global::Pulumi.ResourceArgs
    {
        [Input("configMapName")]
        public Input<string>? ConfigMapName { get; set; }

        [Input("resolveKey")]
        public Input<string>? ResolveKey { get; set; }

        public StarRocksClusterSpecStarrockscnspecConfigmapinfoArgs()
        {
        }
        public static new StarRocksClusterSpecStarrockscnspecConfigmapinfoArgs Empty => new StarRocksClusterSpecStarrockscnspecConfigmapinfoArgs();
    }
}
