// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using Pulumi;

namespace Unilake.Iac.Kubernetes.Custom.Crds.StarRock.V1Alpha1.Inputs
{

    public class StarRocksClusterSpecStarrocksfespecHostaliasesArgs : global::Pulumi.ResourceArgs
    {
        [Input("hostnames")]
        private InputList<string>? _hostnames;
        public InputList<string> Hostnames
        {
            get => _hostnames ?? (_hostnames = new InputList<string>());
            set => _hostnames = value;
        }

        [Input("ip")]
        public Input<string>? Ip { get; set; }

        public StarRocksClusterSpecStarrocksfespecHostaliasesArgs()
        {
        }
        public static new StarRocksClusterSpecStarrocksfespecHostaliasesArgs Empty => new StarRocksClusterSpecStarrocksfespecHostaliasesArgs();
    }
}
