// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using Pulumi;

namespace Unilake.Iac.Kubernetes.Custom.Crds.StarRock.V1Alpha1.Inputs
{

    public class StarRocksClusterStatusStarrocksbestatusArgs : global::Pulumi.ResourceArgs
    {
        [Input("creatingInstances")]
        private InputList<string>? _creatingInstances;
        public InputList<string> CreatingInstances
        {
            get => _creatingInstances ?? (_creatingInstances = new InputList<string>());
            set => _creatingInstances = value;
        }

        [Input("failedInstances")]
        private InputList<string>? _failedInstances;
        public InputList<string> FailedInstances
        {
            get => _failedInstances ?? (_failedInstances = new InputList<string>());
            set => _failedInstances = value;
        }

        [Input("phase", required: true)]
        public Input<string> Phase { get; set; } = null!;

        [Input("reason")]
        public Input<string>? Reason { get; set; }

        [Input("resourceNames")]
        private InputList<string>? _resourceNames;
        public InputList<string> ResourceNames
        {
            get => _resourceNames ?? (_resourceNames = new InputList<string>());
            set => _resourceNames = value;
        }

        [Input("runningInstances")]
        private InputList<string>? _runningInstances;
        public InputList<string> RunningInstances
        {
            get => _runningInstances ?? (_runningInstances = new InputList<string>());
            set => _runningInstances = value;
        }

        [Input("serviceName")]
        public Input<string>? ServiceName { get; set; }

        public StarRocksClusterStatusStarrocksbestatusArgs()
        {
        }
        public static new StarRocksClusterStatusStarrocksbestatusArgs Empty => new StarRocksClusterStatusStarrocksbestatusArgs();
    }
}
