// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using Pulumi;

namespace Unilake.Iac.Kubernetes.Custom.Crds.StarRock.V1Alpha1.Inputs
{

    public class StarRocksClusterSpecStarrockscnspecAffinityPodaffinityPreferredduringschedulingignoredduringexecutionArgs : global::Pulumi.ResourceArgs
    {
        [Input("podAffinityTerm", required: true)]
        public Input<StarRocksClusterSpecStarrockscnspecAffinityPodaffinityPreferredduringschedulingignoredduringexecutionPodaffinitytermArgs> PodAffinityTerm { get; set; } = null!;

        [Input("weight", required: true)]
        public Input<int> Weight { get; set; } = null!;

        public StarRocksClusterSpecStarrockscnspecAffinityPodaffinityPreferredduringschedulingignoredduringexecutionArgs()
        {
        }
        public static new StarRocksClusterSpecStarrockscnspecAffinityPodaffinityPreferredduringschedulingignoredduringexecutionArgs Empty => new StarRocksClusterSpecStarrockscnspecAffinityPodaffinityPreferredduringschedulingignoredduringexecutionArgs();
    }
}
