// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using Pulumi;

namespace Unilake.Iac.Kubernetes.Custom.Crds.StarRock.V1Alpha1.Inputs
{

    public class StarRocksClusterSpecStarrockscnspecAutoscalingpolicyArgs : global::Pulumi.ResourceArgs
    {
        [Input("hpaPolicy")]
        public Input<StarRocksClusterSpecStarrockscnspecAutoscalingpolicyHpapolicyArgs>? HpaPolicy { get; set; }

        [Input("maxReplicas")]
        public Input<int>? MaxReplicas { get; set; }

        [Input("minReplicas")]
        public Input<int>? MinReplicas { get; set; }

        [Input("version")]
        public Input<string>? Version { get; set; }

        public StarRocksClusterSpecStarrockscnspecAutoscalingpolicyArgs()
        {
            Version = "v2beta2";
        }
        public static new StarRocksClusterSpecStarrockscnspecAutoscalingpolicyArgs Empty => new StarRocksClusterSpecStarrockscnspecAutoscalingpolicyArgs();
    }
}
