// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using Pulumi;

namespace Unilake.Iac.Kubernetes.Custom.Crds.StarRock.V1Alpha1.Outputs
{

    [OutputType]
    public sealed class StarRocksClusterSpecStarrockscnspecAutoscalingpolicyHpapolicyBehavior
    {
        public readonly StarRocksClusterSpecStarrockscnspecAutoscalingpolicyHpapolicyBehaviorScaledown ScaleDown;
        public readonly StarRocksClusterSpecStarrockscnspecAutoscalingpolicyHpapolicyBehaviorScaleup ScaleUp;

        [OutputConstructor]
        private StarRocksClusterSpecStarrockscnspecAutoscalingpolicyHpapolicyBehavior(
            StarRocksClusterSpecStarrockscnspecAutoscalingpolicyHpapolicyBehaviorScaledown scaleDown,

            StarRocksClusterSpecStarrockscnspecAutoscalingpolicyHpapolicyBehaviorScaleup scaleUp)
        {
            ScaleDown = scaleDown;
            ScaleUp = scaleUp;
        }
    }
}
