// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using Pulumi;

namespace Unilake.Iac.Kubernetes.Custom.Crds.StarRock.V1Alpha1.Outputs
{

    [OutputType]
    public sealed class StarRocksClusterStatus
    {
        public readonly string Phase;
        public readonly StarRocksClusterStatusStarrocksbestatus StarRocksBeStatus;
        public readonly StarRocksClusterStatusStarrockscnstatus StarRocksCnStatus;
        public readonly StarRocksClusterStatusStarrocksfestatus StarRocksFeStatus;

        [OutputConstructor]
        private StarRocksClusterStatus(
            string phase,

            StarRocksClusterStatusStarrocksbestatus starRocksBeStatus,

            StarRocksClusterStatusStarrockscnstatus starRocksCnStatus,

            StarRocksClusterStatusStarrocksfestatus starRocksFeStatus)
        {
            Phase = phase;
            StarRocksBeStatus = starRocksBeStatus;
            StarRocksCnStatus = starRocksCnStatus;
            StarRocksFeStatus = starRocksFeStatus;
        }
    }
}
