// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using Pulumi;

namespace Unilake.Iac.Kubernetes.Custom.Crds.StarRock.V1Alpha1.Outputs
{

    [OutputType]
    public sealed class StarRocksClusterSpecStarrocksbespecBeenvvarsValuefromResourcefieldref
    {
        public readonly string ContainerName;
        public readonly Union<int, string> Divisor;
        public readonly string Resource;

        [OutputConstructor]
        private StarRocksClusterSpecStarrocksbespecBeenvvarsValuefromResourcefieldref(
            string containerName,

            Union<int, string> divisor,

            string resource)
        {
            ContainerName = containerName;
            Divisor = divisor;
            Resource = resource;
        }
    }
}
