// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using Pulumi;

namespace Unilake.Iac.Kubernetes.Custom.Crds.StarRock.V1Alpha1.Outputs
{

    [OutputType]
    public sealed class StarRocksClusterSpecStarrocksfespecAffinityNodeaffinityPreferredduringschedulingignoredduringexecution
    {
        public readonly StarRocksClusterSpecStarrocksfespecAffinityNodeaffinityPreferredduringschedulingignoredduringexecutionPreference Preference;
        public readonly int Weight;

        [OutputConstructor]
        private StarRocksClusterSpecStarrocksfespecAffinityNodeaffinityPreferredduringschedulingignoredduringexecution(
            StarRocksClusterSpecStarrocksfespecAffinityNodeaffinityPreferredduringschedulingignoredduringexecutionPreference preference,

            int weight)
        {
            Preference = preference;
            Weight = weight;
        }
    }
}
