// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using Pulumi;

namespace Unilake.Iac.Kubernetes.Custom.Crds.StarRock.V1Alpha1.Outputs
{

    [OutputType]
    public sealed class StarRocksClusterSpecStarrocksbespecTolerations
    {
        public readonly string Effect;
        public readonly string Key;
        public readonly string Operator;
        public readonly int TolerationSeconds;
        public readonly string Value;

        [OutputConstructor]
        private StarRocksClusterSpecStarrocksbespecTolerations(
            string effect,

            string key,

            string @operator,

            int tolerationSeconds,

            string value)
        {
            Effect = effect;
            Key = key;
            Operator = @operator;
            TolerationSeconds = tolerationSeconds;
            Value = value;
        }
    }
}
