// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using Pulumi;

namespace Unilake.Iac.Kubernetes.Custom.Crds.StarRock.V1Alpha1.Outputs
{

    [OutputType]
    public sealed class StarRocksClusterSpecStarrockscnspecAutoscalingpolicyHpapolicyMetricsPodsMetric
    {
        public readonly string Name;
        public readonly StarRocksClusterSpecStarrockscnspecAutoscalingpolicyHpapolicyMetricsPodsMetricSelector Selector;

        [OutputConstructor]
        private StarRocksClusterSpecStarrockscnspecAutoscalingpolicyHpapolicyMetricsPodsMetric(
            string name,

            StarRocksClusterSpecStarrockscnspecAutoscalingpolicyHpapolicyMetricsPodsMetricSelector selector)
        {
            Name = name;
            Selector = selector;
        }
    }
}
