// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using Pulumi;

namespace Unilake.Iac.Kubernetes.Custom.Crds.StarRock.V1Alpha1.Outputs
{

    [OutputType]
    public sealed class StarRocksClusterSpecStarrocksbespecStoragevolumes
    {
        public readonly string MountPath;
        public readonly string Name;
        public readonly string StorageClassName;
        public readonly string StorageSize;

        [OutputConstructor]
        private StarRocksClusterSpecStarrocksbespecStoragevolumes(
            string mountPath,

            string name,

            string storageClassName,

            string storageSize)
        {
            MountPath = mountPath;
            Name = name;
            StorageClassName = storageClassName;
            StorageSize = storageSize;
        }
    }
}
