// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using Pulumi;

namespace Unilake.Iac.Kubernetes.Custom.Crds.StarRock.V1Alpha1.Outputs
{

    [OutputType]
    public sealed class StarRocksClusterSpecStarrocksbespecBeenvvarsValuefrom
    {
        public readonly StarRocksClusterSpecStarrocksbespecBeenvvarsValuefromConfigmapkeyref ConfigMapKeyRef;
        public readonly StarRocksClusterSpecStarrocksbespecBeenvvarsValuefromFieldref FieldRef;
        public readonly StarRocksClusterSpecStarrocksbespecBeenvvarsValuefromResourcefieldref ResourceFieldRef;
        public readonly StarRocksClusterSpecStarrocksbespecBeenvvarsValuefromSecretkeyref SecretKeyRef;

        [OutputConstructor]
        private StarRocksClusterSpecStarrocksbespecBeenvvarsValuefrom(
            StarRocksClusterSpecStarrocksbespecBeenvvarsValuefromConfigmapkeyref configMapKeyRef,

            StarRocksClusterSpecStarrocksbespecBeenvvarsValuefromFieldref fieldRef,

            StarRocksClusterSpecStarrocksbespecBeenvvarsValuefromResourcefieldref resourceFieldRef,

            StarRocksClusterSpecStarrocksbespecBeenvvarsValuefromSecretkeyref secretKeyRef)
        {
            ConfigMapKeyRef = configMapKeyRef;
            FieldRef = fieldRef;
            ResourceFieldRef = resourceFieldRef;
            SecretKeyRef = secretKeyRef;
        }
    }
}
