// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using Pulumi;

namespace Unilake.Iac.Kubernetes.Custom.Crds.StarRock.V1Alpha1.Outputs
{

    [OutputType]
    public sealed class StarRocksClusterSpecStarrocksbespecBeenvvarsValuefromFieldref
    {
        public readonly string ApiVersion;
        public readonly string FieldPath;

        [OutputConstructor]
        private StarRocksClusterSpecStarrocksbespecBeenvvarsValuefromFieldref(
            string apiVersion,

            string fieldPath)
        {
            ApiVersion = apiVersion;
            FieldPath = fieldPath;
        }
    }
}
