// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using Pulumi;

namespace Unilake.Iac.Kubernetes.Custom.Crds.StarRock.V1Alpha1.Outputs
{

    [OutputType]
    public sealed class StarRocksClusterSpecStarrockscnspecAutoscalingpolicy
    {
        public readonly StarRocksClusterSpecStarrockscnspecAutoscalingpolicyHpapolicy HpaPolicy;
        public readonly int MaxReplicas;
        public readonly int MinReplicas;
        public readonly string Version;

        [OutputConstructor]
        private StarRocksClusterSpecStarrockscnspecAutoscalingpolicy(
            StarRocksClusterSpecStarrockscnspecAutoscalingpolicyHpapolicy hpaPolicy,

            int maxReplicas,

            int minReplicas,

            string version)
        {
            HpaPolicy = hpaPolicy;
            MaxReplicas = maxReplicas;
            MinReplicas = minReplicas;
            Version = version;
        }
    }
}
