// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using Pulumi;

namespace Unilake.Iac.Kubernetes.Custom.Crds.StarRock.V1Alpha1.Outputs
{

    [OutputType]
    public sealed class StarRocksClusterSpecStarrockscnspecAutoscalingpolicyHpapolicyMetricsResourceTarget
    {
        public readonly int AverageUtilization;
        public readonly Union<int, string> AverageValue;
        public readonly string Type;
        public readonly Union<int, string> Value;

        [OutputConstructor]
        private StarRocksClusterSpecStarrockscnspecAutoscalingpolicyHpapolicyMetricsResourceTarget(
            int averageUtilization,

            Union<int, string> averageValue,

            string type,

            Union<int, string> value)
        {
            AverageUtilization = averageUtilization;
            AverageValue = averageValue;
            Type = type;
            Value = value;
        }
    }
}
