// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using Pulumi;

namespace Unilake.Iac.Kubernetes.Custom.Crds.StarRock.V1Alpha1.Outputs
{

    [OutputType]
    public sealed class StarRocksClusterSpecStarrocksfespecFeenvvarsValuefrom
    {
        public readonly StarRocksClusterSpecStarrocksfespecFeenvvarsValuefromConfigmapkeyref ConfigMapKeyRef;
        public readonly StarRocksClusterSpecStarrocksfespecFeenvvarsValuefromFieldref FieldRef;
        public readonly StarRocksClusterSpecStarrocksfespecFeenvvarsValuefromResourcefieldref ResourceFieldRef;
        public readonly StarRocksClusterSpecStarrocksfespecFeenvvarsValuefromSecretkeyref SecretKeyRef;

        [OutputConstructor]
        private StarRocksClusterSpecStarrocksfespecFeenvvarsValuefrom(
            StarRocksClusterSpecStarrocksfespecFeenvvarsValuefromConfigmapkeyref configMapKeyRef,

            StarRocksClusterSpecStarrocksfespecFeenvvarsValuefromFieldref fieldRef,

            StarRocksClusterSpecStarrocksfespecFeenvvarsValuefromResourcefieldref resourceFieldRef,

            StarRocksClusterSpecStarrocksfespecFeenvvarsValuefromSecretkeyref secretKeyRef)
        {
            ConfigMapKeyRef = configMapKeyRef;
            FieldRef = fieldRef;
            ResourceFieldRef = resourceFieldRef;
            SecretKeyRef = secretKeyRef;
        }
    }
}
