// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using Pulumi;

namespace Unilake.Iac.Kubernetes.Custom.Crds.StarRock.V1Alpha1.Outputs
{

    [OutputType]
    public sealed class StarRocksClusterSpecStarrockscnspecCnenvvarsValuefrom
    {
        public readonly StarRocksClusterSpecStarrockscnspecCnenvvarsValuefromConfigmapkeyref ConfigMapKeyRef;
        public readonly StarRocksClusterSpecStarrockscnspecCnenvvarsValuefromFieldref FieldRef;
        public readonly StarRocksClusterSpecStarrockscnspecCnenvvarsValuefromResourcefieldref ResourceFieldRef;
        public readonly StarRocksClusterSpecStarrockscnspecCnenvvarsValuefromSecretkeyref SecretKeyRef;

        [OutputConstructor]
        private StarRocksClusterSpecStarrockscnspecCnenvvarsValuefrom(
            StarRocksClusterSpecStarrockscnspecCnenvvarsValuefromConfigmapkeyref configMapKeyRef,

            StarRocksClusterSpecStarrockscnspecCnenvvarsValuefromFieldref fieldRef,

            StarRocksClusterSpecStarrockscnspecCnenvvarsValuefromResourcefieldref resourceFieldRef,

            StarRocksClusterSpecStarrockscnspecCnenvvarsValuefromSecretkeyref secretKeyRef)
        {
            ConfigMapKeyRef = configMapKeyRef;
            FieldRef = fieldRef;
            ResourceFieldRef = resourceFieldRef;
            SecretKeyRef = secretKeyRef;
        }
    }
}
