// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using Pulumi;

namespace Unilake.Iac.Kubernetes.Custom.Crds.StarRock.V1Alpha1.Outputs
{

    [OutputType]
    public sealed class StarRocksClusterSpecStarrocksbespecConfigmapinfo
    {
        public readonly string ConfigMapName;
        public readonly string ResolveKey;

        [OutputConstructor]
        private StarRocksClusterSpecStarrocksbespecConfigmapinfo(
            string configMapName,

            string resolveKey)
        {
            ConfigMapName = configMapName;
            ResolveKey = resolveKey;
        }
    }
}
