// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System.Collections.Immutable;
using Pulumi;

namespace Unilake.Iac.Kubernetes.Custom.Crds.StarRock.V1Alpha1.Outputs
{

    [OutputType]
    public sealed class StarRocksClusterStatusStarrockscnstatus
    {
        public readonly ImmutableArray<string> CreatingInstances;
        public readonly ImmutableArray<string> FailedInstances;
        public readonly StarRocksClusterStatusStarrockscnstatusHorizontalscaler HorizontalScaler;
        public readonly string HpaName;
        public readonly string Phase;
        public readonly string Reason;
        public readonly ImmutableArray<string> ResourceNames;
        public readonly ImmutableArray<string> RunningInstances;
        public readonly string ServiceName;

        [OutputConstructor]
        private StarRocksClusterStatusStarrockscnstatus(
            ImmutableArray<string> creatingInstances,

            ImmutableArray<string> failedInstances,

            StarRocksClusterStatusStarrockscnstatusHorizontalscaler horizontalScaler,

            string hpaName,

            string phase,

            string reason,

            ImmutableArray<string> resourceNames,

            ImmutableArray<string> runningInstances,

            string serviceName)
        {
            CreatingInstances = creatingInstances;
            FailedInstances = failedInstances;
            HorizontalScaler = horizontalScaler;
            HpaName = hpaName;
            Phase = phase;
            Reason = reason;
            ResourceNames = resourceNames;
            RunningInstances = runningInstances;
            ServiceName = serviceName;
        }
    }
}
