// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using Pulumi;

namespace Unilake.Iac.Kubernetes.Custom.Crds.StarRock.V1Alpha1.Outputs
{

    [OutputType]
    public sealed class StarRocksClusterSpecStarrocksbespecProbe
    {
        public readonly int InitialDelaySeconds;
        public readonly int PeriodSeconds;
        public readonly string Type;

        [OutputConstructor]
        private StarRocksClusterSpecStarrocksbespecProbe(
            int initialDelaySeconds,

            int periodSeconds,

            string type)
        {
            InitialDelaySeconds = initialDelaySeconds;
            PeriodSeconds = periodSeconds;
            Type = type;
        }
    }
}
