// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System.Collections.Immutable;
using Pulumi;

namespace Unilake.Iac.Kubernetes.Custom.Crds.StarRock.V1Alpha1.Outputs
{

    [OutputType]
    public sealed class StarRocksClusterSpecStarrocksbespecHostaliases
    {
        public readonly ImmutableArray<string> Hostnames;
        public readonly string Ip;

        [OutputConstructor]
        private StarRocksClusterSpecStarrocksbespecHostaliases(
            ImmutableArray<string> hostnames,

            string ip)
        {
            Hostnames = hostnames;
            Ip = ip;
        }
    }
}
