// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using Pulumi;

namespace Unilake.Iac.Kubernetes.Custom.Crds.StarRock.V1Alpha1.Outputs
{

    [OutputType]
    public sealed class StarRocksClusterSpecStarrockscnspecAutoscalingpolicyHpapolicyMetricsObject
    {
        public readonly StarRocksClusterSpecStarrockscnspecAutoscalingpolicyHpapolicyMetricsObjectDescribedobject DescribedObject;
        public readonly StarRocksClusterSpecStarrockscnspecAutoscalingpolicyHpapolicyMetricsObjectMetric Metric;
        public readonly StarRocksClusterSpecStarrockscnspecAutoscalingpolicyHpapolicyMetricsObjectTarget Target;

        [OutputConstructor]
        private StarRocksClusterSpecStarrockscnspecAutoscalingpolicyHpapolicyMetricsObject(
            StarRocksClusterSpecStarrockscnspecAutoscalingpolicyHpapolicyMetricsObjectDescribedobject describedObject,

            StarRocksClusterSpecStarrockscnspecAutoscalingpolicyHpapolicyMetricsObjectMetric metric,

            StarRocksClusterSpecStarrockscnspecAutoscalingpolicyHpapolicyMetricsObjectTarget target)
        {
            DescribedObject = describedObject;
            Metric = metric;
            Target = target;
        }
    }
}
