// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using Pulumi;

namespace Unilake.Iac.Kubernetes.Custom.Crds.StarRock.V1Alpha1.Outputs
{

    [OutputType]
    public sealed class StarRocksClusterSpec
    {
        public readonly string ServiceAccount;
        public readonly StarRocksClusterSpecStarrocksbespec StarRocksBeSpec;
        public readonly StarRocksClusterSpecStarrockscnspec StarRocksCnSpec;
        public readonly StarRocksClusterSpecStarrocksfespec StarRocksFeSpec;

        [OutputConstructor]
        private StarRocksClusterSpec(
            string serviceAccount,

            StarRocksClusterSpecStarrocksbespec starRocksBeSpec,

            StarRocksClusterSpecStarrockscnspec starRocksCnSpec,

            StarRocksClusterSpecStarrocksfespec starRocksFeSpec)
        {
            ServiceAccount = serviceAccount;
            StarRocksBeSpec = starRocksBeSpec;
            StarRocksCnSpec = starRocksCnSpec;
            StarRocksFeSpec = starRocksFeSpec;
        }
    }
}
