// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System.Collections.Immutable;
using Pulumi;

namespace Unilake.Iac.Kubernetes.Custom.Crds.StarRock.V1Alpha1.Outputs
{

    [OutputType]
    public sealed class StarRocksClusterSpecStarrocksbespec
    {
        public readonly StarRocksClusterSpecStarrocksbespecAffinity Affinity;
        public readonly ImmutableDictionary<string, string> Annotations;
        public readonly ImmutableArray<StarRocksClusterSpecStarrocksbespecBeenvvars> BeEnvVars;
        public readonly StarRocksClusterSpecStarrocksbespecConfigmapinfo ConfigMapInfo;
        public readonly int FsGroup;
        public readonly ImmutableArray<StarRocksClusterSpecStarrocksbespecHostaliases> HostAliases;
        public readonly string Image;
        public readonly ImmutableArray<StarRocksClusterSpecStarrocksbespecImagepullsecrets> ImagePullSecrets;
        public readonly ImmutableDictionary<string, Union<int, string>> Limits;
        public readonly string Name;
        public readonly ImmutableDictionary<string, string> NodeSelector;
        public readonly ImmutableDictionary<string, string> PodLabels;
        public readonly StarRocksClusterSpecStarrocksbespecProbe Probe;
        public readonly ImmutableArray<string> ReplicaInstances;
        public readonly int Replicas;
        public readonly ImmutableDictionary<string, Union<int, string>> Requests;
        public readonly StarRocksClusterSpecStarrocksbespecService Service;
        public readonly string ServiceAccount;
        public readonly ImmutableArray<StarRocksClusterSpecStarrocksbespecStoragevolumes> StorageVolumes;
        public readonly ImmutableArray<StarRocksClusterSpecStarrocksbespecTolerations> Tolerations;

        [OutputConstructor]
        private StarRocksClusterSpecStarrocksbespec(
            StarRocksClusterSpecStarrocksbespecAffinity affinity,

            ImmutableDictionary<string, string> annotations,

            ImmutableArray<StarRocksClusterSpecStarrocksbespecBeenvvars> beEnvVars,

            StarRocksClusterSpecStarrocksbespecConfigmapinfo configMapInfo,

            int fsGroup,

            ImmutableArray<StarRocksClusterSpecStarrocksbespecHostaliases> hostAliases,

            string image,

            ImmutableArray<StarRocksClusterSpecStarrocksbespecImagepullsecrets> imagePullSecrets,

            ImmutableDictionary<string, Union<int, string>> limits,

            string name,

            ImmutableDictionary<string, string> nodeSelector,

            ImmutableDictionary<string, string> podLabels,

            StarRocksClusterSpecStarrocksbespecProbe probe,

            ImmutableArray<string> replicaInstances,

            int replicas,

            ImmutableDictionary<string, Union<int, string>> requests,

            StarRocksClusterSpecStarrocksbespecService service,

            string serviceAccount,

            ImmutableArray<StarRocksClusterSpecStarrocksbespecStoragevolumes> storageVolumes,

            ImmutableArray<StarRocksClusterSpecStarrocksbespecTolerations> tolerations)
        {
            Affinity = affinity;
            Annotations = annotations;
            BeEnvVars = beEnvVars;
            ConfigMapInfo = configMapInfo;
            FsGroup = fsGroup;
            HostAliases = hostAliases;
            Image = image;
            ImagePullSecrets = imagePullSecrets;
            Limits = limits;
            Name = name;
            NodeSelector = nodeSelector;
            PodLabels = podLabels;
            Probe = probe;
            ReplicaInstances = replicaInstances;
            Replicas = replicas;
            Requests = requests;
            Service = service;
            ServiceAccount = serviceAccount;
            StorageVolumes = storageVolumes;
            Tolerations = tolerations;
        }
    }
}
