// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System.Collections.Immutable;
using Pulumi;

namespace Unilake.Iac.Kubernetes.Custom.Crds.StarRock.V1Alpha1.Outputs
{

    [OutputType]
    public sealed class StarRocksClusterSpecStarrockscnspecAutoscalingpolicyHpapolicyBehaviorScaleup
    {
        public readonly ImmutableArray<StarRocksClusterSpecStarrockscnspecAutoscalingpolicyHpapolicyBehaviorScaleupPolicies> Policies;
        public readonly string SelectPolicy;
        public readonly int StabilizationWindowSeconds;

        [OutputConstructor]
        private StarRocksClusterSpecStarrockscnspecAutoscalingpolicyHpapolicyBehaviorScaleup(
            ImmutableArray<StarRocksClusterSpecStarrockscnspecAutoscalingpolicyHpapolicyBehaviorScaleupPolicies> policies,

            string selectPolicy,

            int stabilizationWindowSeconds)
        {
            Policies = policies;
            SelectPolicy = selectPolicy;
            StabilizationWindowSeconds = stabilizationWindowSeconds;
        }
    }
}
