// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using Pulumi;

namespace Unilake.Iac.Kubernetes.Custom.Crds.StarRock.V1Alpha1.Outputs
{

    [OutputType]
    public sealed class StarRocksClusterSpecStarrocksbespecBeenvvarsValuefromConfigmapkeyref
    {
        public readonly string Key;
        public readonly string Name;
        public readonly bool Optional;

        [OutputConstructor]
        private StarRocksClusterSpecStarrocksbespecBeenvvarsValuefromConfigmapkeyref(
            string key,

            string name,

            bool optional)
        {
            Key = key;
            Name = name;
            Optional = optional;
        }
    }
}
