// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using Pulumi;

namespace Unilake.Iac.Kubernetes.Custom.Crds.StarRock.V1Alpha1.Outputs
{

    [OutputType]
    public sealed class StarRocksClusterSpecStarrockscnspecAutoscalingpolicyHpapolicyMetricsContainerresource
    {
        public readonly string Container;
        public readonly string Name;
        public readonly StarRocksClusterSpecStarrockscnspecAutoscalingpolicyHpapolicyMetricsContainerresourceTarget Target;

        [OutputConstructor]
        private StarRocksClusterSpecStarrockscnspecAutoscalingpolicyHpapolicyMetricsContainerresource(
            string container,

            string name,

            StarRocksClusterSpecStarrockscnspecAutoscalingpolicyHpapolicyMetricsContainerresourceTarget target)
        {
            Container = container;
            Name = name;
            Target = target;
        }
    }
}
