// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using Pulumi;

namespace Unilake.Iac.Kubernetes.Custom.Crds.StarRock.V1Alpha1.Outputs
{

    [OutputType]
    public sealed class StarRocksClusterSpecStarrocksbespecAffinity
    {
        public readonly StarRocksClusterSpecStarrocksbespecAffinityNodeaffinity NodeAffinity;
        public readonly StarRocksClusterSpecStarrocksbespecAffinityPodaffinity PodAffinity;
        public readonly StarRocksClusterSpecStarrocksbespecAffinityPodantiaffinity PodAntiAffinity;

        [OutputConstructor]
        private StarRocksClusterSpecStarrocksbespecAffinity(
            StarRocksClusterSpecStarrocksbespecAffinityNodeaffinity nodeAffinity,

            StarRocksClusterSpecStarrocksbespecAffinityPodaffinity podAffinity,

            StarRocksClusterSpecStarrocksbespecAffinityPodantiaffinity podAntiAffinity)
        {
            NodeAffinity = nodeAffinity;
            PodAffinity = podAffinity;
            PodAntiAffinity = podAntiAffinity;
        }
    }
}
