// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System.Collections.Immutable;
using Pulumi;

namespace Unilake.Iac.Kubernetes.Custom.Crds.StarRock.V1Alpha1.Outputs
{

    [OutputType]
    public sealed class StarRocksClusterSpecStarrockscnspec
    {
        public readonly StarRocksClusterSpecStarrockscnspecAffinity Affinity;
        public readonly ImmutableDictionary<string, string> Annotations;
        public readonly StarRocksClusterSpecStarrockscnspecAutoscalingpolicy AutoScalingPolicy;
        public readonly ImmutableArray<StarRocksClusterSpecStarrockscnspecCnenvvars> CnEnvVars;
        public readonly StarRocksClusterSpecStarrockscnspecConfigmapinfo ConfigMapInfo;
        public readonly int FsGroup;
        public readonly ImmutableArray<StarRocksClusterSpecStarrockscnspecHostaliases> HostAliases;
        public readonly string Image;
        public readonly ImmutableArray<StarRocksClusterSpecStarrockscnspecImagepullsecrets> ImagePullSecrets;
        public readonly ImmutableDictionary<string, Union<int, string>> Limits;
        public readonly string Name;
        public readonly ImmutableDictionary<string, string> NodeSelector;
        public readonly ImmutableDictionary<string, string> PodLabels;
        public readonly StarRocksClusterSpecStarrockscnspecProbe Probe;
        public readonly int Replicas;
        public readonly ImmutableDictionary<string, Union<int, string>> Requests;
        public readonly StarRocksClusterSpecStarrockscnspecService Service;
        public readonly string ServiceAccount;
        public readonly ImmutableArray<StarRocksClusterSpecStarrockscnspecTolerations> Tolerations;

        [OutputConstructor]
        private StarRocksClusterSpecStarrockscnspec(
            StarRocksClusterSpecStarrockscnspecAffinity affinity,

            ImmutableDictionary<string, string> annotations,

            StarRocksClusterSpecStarrockscnspecAutoscalingpolicy autoScalingPolicy,

            ImmutableArray<StarRocksClusterSpecStarrockscnspecCnenvvars> cnEnvVars,

            StarRocksClusterSpecStarrockscnspecConfigmapinfo configMapInfo,

            int fsGroup,

            ImmutableArray<StarRocksClusterSpecStarrockscnspecHostaliases> hostAliases,

            string image,

            ImmutableArray<StarRocksClusterSpecStarrockscnspecImagepullsecrets> imagePullSecrets,

            ImmutableDictionary<string, Union<int, string>> limits,

            string name,

            ImmutableDictionary<string, string> nodeSelector,

            ImmutableDictionary<string, string> podLabels,

            StarRocksClusterSpecStarrockscnspecProbe probe,

            int replicas,

            ImmutableDictionary<string, Union<int, string>> requests,

            StarRocksClusterSpecStarrockscnspecService service,

            string serviceAccount,

            ImmutableArray<StarRocksClusterSpecStarrockscnspecTolerations> tolerations)
        {
            Affinity = affinity;
            Annotations = annotations;
            AutoScalingPolicy = autoScalingPolicy;
            CnEnvVars = cnEnvVars;
            ConfigMapInfo = configMapInfo;
            FsGroup = fsGroup;
            HostAliases = hostAliases;
            Image = image;
            ImagePullSecrets = imagePullSecrets;
            Limits = limits;
            Name = name;
            NodeSelector = nodeSelector;
            PodLabels = podLabels;
            Probe = probe;
            Replicas = replicas;
            Requests = requests;
            Service = service;
            ServiceAccount = serviceAccount;
            Tolerations = tolerations;
        }
    }
}
