// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using Pulumi;

namespace Unilake.Iac.Kubernetes.Custom.Crds.StarRock.V1Alpha1.Outputs
{

    [OutputType]
    public sealed class StarRocksClusterSpecStarrockscnspecAutoscalingpolicyHpapolicyMetricsExternalMetric
    {
        public readonly string Name;
        public readonly StarRocksClusterSpecStarrockscnspecAutoscalingpolicyHpapolicyMetricsExternalMetricSelector Selector;

        [OutputConstructor]
        private StarRocksClusterSpecStarrockscnspecAutoscalingpolicyHpapolicyMetricsExternalMetric(
            string name,

            StarRocksClusterSpecStarrockscnspecAutoscalingpolicyHpapolicyMetricsExternalMetricSelector selector)
        {
            Name = name;
            Selector = selector;
        }
    }
}
