// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System.Collections.Immutable;
using Pulumi;

namespace Unilake.Iac.Kubernetes.Custom.Crds.StarRock.V1Alpha1.Outputs
{

    [OutputType]
    public sealed class StarRocksClusterSpecStarrockscnspecAffinityNodeaffinityRequiredduringschedulingignoredduringexecution
    {
        public readonly ImmutableArray<StarRocksClusterSpecStarrockscnspecAffinityNodeaffinityRequiredduringschedulingignoredduringexecutionNodeselectorterms> NodeSelectorTerms;

        [OutputConstructor]
        private StarRocksClusterSpecStarrockscnspecAffinityNodeaffinityRequiredduringschedulingignoredduringexecution(ImmutableArray<StarRocksClusterSpecStarrockscnspecAffinityNodeaffinityRequiredduringschedulingignoredduringexecutionNodeselectorterms> nodeSelectorTerms)
        {
            NodeSelectorTerms = nodeSelectorTerms;
        }
    }
}
