// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using Pulumi;

namespace Unilake.Iac.Kubernetes.Custom.Crds.StarRock.V1Alpha1.Outputs
{

    [OutputType]
    public sealed class StarRocksClusterSpecStarrockscnspecAutoscalingpolicyHpapolicyMetricsExternal
    {
        public readonly StarRocksClusterSpecStarrockscnspecAutoscalingpolicyHpapolicyMetricsExternalMetric Metric;
        public readonly StarRocksClusterSpecStarrockscnspecAutoscalingpolicyHpapolicyMetricsExternalTarget Target;

        [OutputConstructor]
        private StarRocksClusterSpecStarrockscnspecAutoscalingpolicyHpapolicyMetricsExternal(
            StarRocksClusterSpecStarrockscnspecAutoscalingpolicyHpapolicyMetricsExternalMetric metric,

            StarRocksClusterSpecStarrockscnspecAutoscalingpolicyHpapolicyMetricsExternalTarget target)
        {
            Metric = metric;
            Target = target;
        }
    }
}
