// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using Pulumi;

namespace Unilake.Iac.Kubernetes.Custom.Crds.StarRock.V1Alpha1.Outputs
{

    [OutputType]
    public sealed class StarRocksClusterSpecStarrockscnspecAutoscalingpolicyHpapolicyMetrics
    {
        public readonly StarRocksClusterSpecStarrockscnspecAutoscalingpolicyHpapolicyMetricsContainerresource ContainerResource;
        public readonly StarRocksClusterSpecStarrockscnspecAutoscalingpolicyHpapolicyMetricsExternal External;
        public readonly StarRocksClusterSpecStarrockscnspecAutoscalingpolicyHpapolicyMetricsObject Object;
        public readonly StarRocksClusterSpecStarrockscnspecAutoscalingpolicyHpapolicyMetricsPods Pods;
        public readonly StarRocksClusterSpecStarrockscnspecAutoscalingpolicyHpapolicyMetricsResource Resource;
        public readonly string Type;

        [OutputConstructor]
        private StarRocksClusterSpecStarrockscnspecAutoscalingpolicyHpapolicyMetrics(
            StarRocksClusterSpecStarrockscnspecAutoscalingpolicyHpapolicyMetricsContainerresource containerResource,

            StarRocksClusterSpecStarrockscnspecAutoscalingpolicyHpapolicyMetricsExternal external,

            StarRocksClusterSpecStarrockscnspecAutoscalingpolicyHpapolicyMetricsObject @object,

            StarRocksClusterSpecStarrockscnspecAutoscalingpolicyHpapolicyMetricsPods pods,

            StarRocksClusterSpecStarrockscnspecAutoscalingpolicyHpapolicyMetricsResource resource,

            string type)
        {
            ContainerResource = containerResource;
            External = external;
            Object = @object;
            Pods = pods;
            Resource = resource;
            Type = type;
        }
    }
}
