// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using Pulumi;

namespace Unilake.Iac.Kubernetes.Custom.Crds.StarRock.V1Alpha1.Outputs
{

    [OutputType]
    public sealed class StarRocksClusterSpecStarrockscnspecAffinity
    {
        public readonly StarRocksClusterSpecStarrockscnspecAffinityNodeaffinity NodeAffinity;
        public readonly StarRocksClusterSpecStarrockscnspecAffinityPodaffinity PodAffinity;
        public readonly StarRocksClusterSpecStarrockscnspecAffinityPodantiaffinity PodAntiAffinity;

        [OutputConstructor]
        private StarRocksClusterSpecStarrockscnspecAffinity(
            StarRocksClusterSpecStarrockscnspecAffinityNodeaffinity nodeAffinity,

            StarRocksClusterSpecStarrockscnspecAffinityPodaffinity podAffinity,

            StarRocksClusterSpecStarrockscnspecAffinityPodantiaffinity podAntiAffinity)
        {
            NodeAffinity = nodeAffinity;
            PodAffinity = podAffinity;
            PodAntiAffinity = podAntiAffinity;
        }
    }
}
