// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using Pulumi;

namespace Unilake.Iac.Kubernetes.Custom.Crds.StarRock.V1Alpha1.Outputs
{

    [OutputType]
    public sealed class StarRocksClusterSpecStarrockscnspecAutoscalingpolicyHpapolicyMetricsObjectDescribedobject
    {
        public readonly string ApiVersion;
        public readonly string Kind;
        public readonly string Name;

        [OutputConstructor]
        private StarRocksClusterSpecStarrockscnspecAutoscalingpolicyHpapolicyMetricsObjectDescribedobject(
            string apiVersion,

            string kind,

            string name)
        {
            ApiVersion = apiVersion;
            Kind = kind;
            Name = name;
        }
    }
}
