// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System.Collections.Immutable;
using Pulumi;

namespace Unilake.Iac.Kubernetes.Custom.Crds.StarRock.V1Alpha1.Outputs
{

    [OutputType]
    public sealed class StarRocksClusterSpecStarrocksbespecService
    {
        public readonly string LoadBalancerIP;
        public readonly string Name;
        public readonly ImmutableArray<StarRocksClusterSpecStarrocksbespecServicePorts> Ports;
        public readonly string Type;

        [OutputConstructor]
        private StarRocksClusterSpecStarrocksbespecService(
            string loadBalancerIP,

            string name,

            ImmutableArray<StarRocksClusterSpecStarrocksbespecServicePorts> ports,

            string type)
        {
            LoadBalancerIP = loadBalancerIP;
            Name = name;
            Ports = ports;
            Type = type;
        }
    }
}
