// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System.Collections.Immutable;
using Pulumi;

namespace Unilake.Iac.Kubernetes.Custom.Crds.StarRock.V1Alpha1.Outputs
{

    [OutputType]
    public sealed class StarRocksClusterSpecStarrocksbespecAffinityNodeaffinityPreferredduringschedulingignoredduringexecutionPreference
    {
        public readonly ImmutableArray<StarRocksClusterSpecStarrocksbespecAffinityNodeaffinityPreferredduringschedulingignoredduringexecutionPreferenceMatchexpressions> MatchExpressions;
        public readonly ImmutableArray<StarRocksClusterSpecStarrocksbespecAffinityNodeaffinityPreferredduringschedulingignoredduringexecutionPreferenceMatchfields> MatchFields;

        [OutputConstructor]
        private StarRocksClusterSpecStarrocksbespecAffinityNodeaffinityPreferredduringschedulingignoredduringexecutionPreference(
            ImmutableArray<StarRocksClusterSpecStarrocksbespecAffinityNodeaffinityPreferredduringschedulingignoredduringexecutionPreferenceMatchexpressions> matchExpressions,

            ImmutableArray<StarRocksClusterSpecStarrocksbespecAffinityNodeaffinityPreferredduringschedulingignoredduringexecutionPreferenceMatchfields> matchFields)
        {
            MatchExpressions = matchExpressions;
            MatchFields = matchFields;
        }
    }
}
