// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System.Collections.Immutable;
using Pulumi;

namespace Unilake.Iac.Kubernetes.Custom.Crds.StarRock.V1Alpha1.Outputs
{

    [OutputType]
    public sealed class StarRocksClusterSpecStarrocksfespec
    {
        public readonly StarRocksClusterSpecStarrocksfespecAffinity Affinity;
        public readonly ImmutableDictionary<string, string> Annotations;
        public readonly StarRocksClusterSpecStarrocksfespecConfigmapinfo ConfigMapInfo;
        public readonly ImmutableArray<StarRocksClusterSpecStarrocksfespecFeenvvars> FeEnvVars;
        public readonly int FsGroup;
        public readonly ImmutableArray<StarRocksClusterSpecStarrocksfespecHostaliases> HostAliases;
        public readonly string Image;
        public readonly ImmutableArray<StarRocksClusterSpecStarrocksfespecImagepullsecrets> ImagePullSecrets;
        public readonly ImmutableDictionary<string, Union<int, string>> Limits;
        public readonly string Name;
        public readonly ImmutableDictionary<string, string> NodeSelector;
        public readonly ImmutableDictionary<string, string> PodLabels;
        public readonly StarRocksClusterSpecStarrocksfespecProbe Probe;
        public readonly int Replicas;
        public readonly ImmutableDictionary<string, Union<int, string>> Requests;
        public readonly StarRocksClusterSpecStarrocksfespecService Service;
        public readonly string ServiceAccount;
        public readonly ImmutableArray<StarRocksClusterSpecStarrocksfespecStoragevolumes> StorageVolumes;
        public readonly ImmutableArray<StarRocksClusterSpecStarrocksfespecTolerations> Tolerations;

        [OutputConstructor]
        private StarRocksClusterSpecStarrocksfespec(
            StarRocksClusterSpecStarrocksfespecAffinity affinity,

            ImmutableDictionary<string, string> annotations,

            StarRocksClusterSpecStarrocksfespecConfigmapinfo configMapInfo,

            ImmutableArray<StarRocksClusterSpecStarrocksfespecFeenvvars> feEnvVars,

            int fsGroup,

            ImmutableArray<StarRocksClusterSpecStarrocksfespecHostaliases> hostAliases,

            string image,

            ImmutableArray<StarRocksClusterSpecStarrocksfespecImagepullsecrets> imagePullSecrets,

            ImmutableDictionary<string, Union<int, string>> limits,

            string name,

            ImmutableDictionary<string, string> nodeSelector,

            ImmutableDictionary<string, string> podLabels,

            StarRocksClusterSpecStarrocksfespecProbe probe,

            int replicas,

            ImmutableDictionary<string, Union<int, string>> requests,

            StarRocksClusterSpecStarrocksfespecService service,

            string serviceAccount,

            ImmutableArray<StarRocksClusterSpecStarrocksfespecStoragevolumes> storageVolumes,

            ImmutableArray<StarRocksClusterSpecStarrocksfespecTolerations> tolerations)
        {
            Affinity = affinity;
            Annotations = annotations;
            ConfigMapInfo = configMapInfo;
            FeEnvVars = feEnvVars;
            FsGroup = fsGroup;
            HostAliases = hostAliases;
            Image = image;
            ImagePullSecrets = imagePullSecrets;
            Limits = limits;
            Name = name;
            NodeSelector = nodeSelector;
            PodLabels = podLabels;
            Probe = probe;
            Replicas = replicas;
            Requests = requests;
            Service = service;
            ServiceAccount = serviceAccount;
            StorageVolumes = storageVolumes;
            Tolerations = tolerations;
        }
    }
}
