// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using Pulumi;

namespace Unilake.Iac.Kubernetes.Custom.Crds.StarRock.V1Alpha1.Outputs
{

    [OutputType]
    public sealed class StarRocksClusterSpecStarrockscnspecCnenvvars
    {
        public readonly string Name;
        public readonly string Value;
        public readonly StarRocksClusterSpecStarrockscnspecCnenvvarsValuefrom ValueFrom;

        [OutputConstructor]
        private StarRocksClusterSpecStarrockscnspecCnenvvars(
            string name,

            string value,

            StarRocksClusterSpecStarrockscnspecCnenvvarsValuefrom valueFrom)
        {
            Name = name;
            Value = value;
            ValueFrom = valueFrom;
        }
    }
}
