// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using Pulumi;

namespace Unilake.Iac.Kubernetes.Custom.Crds.StarRock.V1Alpha1.Outputs
{

    [OutputType]
    public sealed class StarRocksClusterSpecStarrocksfespecAffinity
    {
        public readonly StarRocksClusterSpecStarrocksfespecAffinityNodeaffinity NodeAffinity;
        public readonly StarRocksClusterSpecStarrocksfespecAffinityPodaffinity PodAffinity;
        public readonly StarRocksClusterSpecStarrocksfespecAffinityPodantiaffinity PodAntiAffinity;

        [OutputConstructor]
        private StarRocksClusterSpecStarrocksfespecAffinity(
            StarRocksClusterSpecStarrocksfespecAffinityNodeaffinity nodeAffinity,

            StarRocksClusterSpecStarrocksfespecAffinityPodaffinity podAffinity,

            StarRocksClusterSpecStarrocksfespecAffinityPodantiaffinity podAntiAffinity)
        {
            NodeAffinity = nodeAffinity;
            PodAffinity = podAffinity;
            PodAntiAffinity = podAntiAffinity;
        }
    }
}
