// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System.Collections.Immutable;
using Pulumi;

namespace Unilake.Iac.Kubernetes.Custom.Crds.StarRock.V1Alpha1.Outputs
{

    [OutputType]
    public sealed class StarRocksClusterSpecStarrockscnspecAutoscalingpolicyHpapolicy
    {
        public readonly StarRocksClusterSpecStarrockscnspecAutoscalingpolicyHpapolicyBehavior Behavior;
        public readonly ImmutableArray<StarRocksClusterSpecStarrockscnspecAutoscalingpolicyHpapolicyMetrics> Metrics;

        [OutputConstructor]
        private StarRocksClusterSpecStarrockscnspecAutoscalingpolicyHpapolicy(
            StarRocksClusterSpecStarrockscnspecAutoscalingpolicyHpapolicyBehavior behavior,

            ImmutableArray<StarRocksClusterSpecStarrockscnspecAutoscalingpolicyHpapolicyMetrics> metrics)
        {
            Behavior = behavior;
            Metrics = metrics;
        }
    }
}
