// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using Pulumi;

namespace Unilake.Iac.Kubernetes.Custom.Crds.StarRock.V1Alpha1.Outputs
{

    [OutputType]
    public sealed class StarRocksClusterSpecStarrockscnspecServicePorts
    {
        public readonly int ContainerPort;
        public readonly string Name;
        public readonly int NodePort;
        public readonly int Port;

        [OutputConstructor]
        private StarRocksClusterSpecStarrockscnspecServicePorts(
            int containerPort,

            string name,

            int nodePort,

            int port)
        {
            ContainerPort = containerPort;
            Name = name;
            NodePort = nodePort;
            Port = port;
        }
    }
}
