// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using Pulumi;

namespace Unilake.Iac.Kubernetes.Custom.Crds.StarRock.V1Alpha1.Outputs
{

    [OutputType]
    public sealed class StarRocksClusterStatusStarrockscnstatusHorizontalscaler
    {
        public readonly string Name;
        public readonly string Version;

        [OutputConstructor]
        private StarRocksClusterStatusStarrockscnstatusHorizontalscaler(
            string name,

            string version)
        {
            Name = name;
            Version = version;
        }
    }
}
